# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_session_generate_title_request import InternalHandlerSessionGenerateTitleRequest

class TestInternalHandlerSessionGenerateTitleRequest(unittest.TestCase):
    """InternalHandlerSessionGenerateTitleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerSessionGenerateTitleRequest:
        """Test InternalHandlerSessionGenerateTitleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerSessionGenerateTitleRequest`
        """
        model = InternalHandlerSessionGenerateTitleRequest()
        if include_optional:
            return InternalHandlerSessionGenerateTitleRequest(
                messages = [
                    weknora.models.github_com_tencent_we_knora_internal_types/message.github_com_Tencent_WeKnora_internal_types.Message(
                        agent_steps = [
                            weknora.models.github_com_tencent_we_knora_internal_types/agent_step.github_com_Tencent_WeKnora_internal_types.AgentStep(
                                iteration = 56, 
                                thought = '', 
                                timestamp = '', 
                                tool_calls = [
                                    weknora.models.github_com_tencent_we_knora_internal_types/tool_call.github_com_Tencent_WeKnora_internal_types.ToolCall(
                                        args = { }, 
                                        duration = 56, 
                                        id = '', 
                                        name = '', 
                                        reflection = '', 
                                        result = weknora.models.result.result(), )
                                    ], )
                            ], 
                        content = '', 
                        created_at = '', 
                        deleted_at = weknora.models.deleted_at.deleted_at(), 
                        id = '', 
                        is_completed = True, 
                        knowledge_references = [
                            weknora.models.github_com_tencent_we_knora_internal_types/search_result.github_com_Tencent_WeKnora_internal_types.SearchResult(
                                chunk_index = 56, 
                                chunk_metadata = [
                                    56
                                    ], 
                                chunk_type = '', 
                                content = '', 
                                end_at = 56, 
                                id = '', 
                                image_info = '', 
                                knowledge_filename = '', 
                                knowledge_id = '', 
                                knowledge_source = '', 
                                knowledge_title = '', 
                                match_type = weknora.models.match_type.match_type(), 
                                metadata = {
                                    'key' : ''
                                    }, 
                                parent_chunk_id = '', 
                                score = 1.337, 
                                seq = 56, 
                                start_at = 56, 
                                sub_chunk_id = [
                                    ''
                                    ], )
                            ], 
                        mentioned_items = [
                            weknora.models.github_com_tencent_we_knora_internal_types/mentioned_item.github_com_Tencent_WeKnora_internal_types.MentionedItem(
                                id = '', 
                                kb_type = '', 
                                name = '', 
                                type = '', )
                            ], 
                        request_id = '', 
                        role = '', 
                        session_id = '', 
                        updated_at = '', )
                    ]
            )
        else:
            return InternalHandlerSessionGenerateTitleRequest(
                messages = [
                    weknora.models.github_com_tencent_we_knora_internal_types/message.github_com_Tencent_WeKnora_internal_types.Message(
                        agent_steps = [
                            weknora.models.github_com_tencent_we_knora_internal_types/agent_step.github_com_Tencent_WeKnora_internal_types.AgentStep(
                                iteration = 56, 
                                thought = '', 
                                timestamp = '', 
                                tool_calls = [
                                    weknora.models.github_com_tencent_we_knora_internal_types/tool_call.github_com_Tencent_WeKnora_internal_types.ToolCall(
                                        args = { }, 
                                        duration = 56, 
                                        id = '', 
                                        name = '', 
                                        reflection = '', 
                                        result = weknora.models.result.result(), )
                                    ], )
                            ], 
                        content = '', 
                        created_at = '', 
                        deleted_at = weknora.models.deleted_at.deleted_at(), 
                        id = '', 
                        is_completed = True, 
                        knowledge_references = [
                            weknora.models.github_com_tencent_we_knora_internal_types/search_result.github_com_Tencent_WeKnora_internal_types.SearchResult(
                                chunk_index = 56, 
                                chunk_metadata = [
                                    56
                                    ], 
                                chunk_type = '', 
                                content = '', 
                                end_at = 56, 
                                id = '', 
                                image_info = '', 
                                knowledge_filename = '', 
                                knowledge_id = '', 
                                knowledge_source = '', 
                                knowledge_title = '', 
                                match_type = weknora.models.match_type.match_type(), 
                                metadata = {
                                    'key' : ''
                                    }, 
                                parent_chunk_id = '', 
                                score = 1.337, 
                                seq = 56, 
                                start_at = 56, 
                                sub_chunk_id = [
                                    ''
                                    ], )
                            ], 
                        mentioned_items = [
                            weknora.models.github_com_tencent_we_knora_internal_types/mentioned_item.github_com_Tencent_WeKnora_internal_types.MentionedItem(
                                id = '', 
                                kb_type = '', 
                                name = '', 
                                type = '', )
                            ], 
                        request_id = '', 
                        role = '', 
                        session_id = '', 
                        updated_at = '', )
                    ],
        )
        """

    def testInternalHandlerSessionGenerateTitleRequest(self):
        """Test InternalHandlerSessionGenerateTitleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
