# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_mcp_service import GithubComTencentWeKnoraInternalTypesMCPService

class TestGithubComTencentWeKnoraInternalTypesMCPService(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesMCPService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesMCPService:
        """Test GithubComTencentWeKnoraInternalTypesMCPService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesMCPService`
        """
        model = GithubComTencentWeKnoraInternalTypesMCPService()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesMCPService(
                advanced_config = weknora.models.github_com_tencent_we_knora_internal_types/mcp_advanced_config.github_com_Tencent_WeKnora_internal_types.MCPAdvancedConfig(
                    retry_count = 56, 
                    retry_delay = 56, 
                    timeout = 56, ),
                auth_config = weknora.models.github_com_tencent_we_knora_internal_types/mcp_auth_config.github_com_Tencent_WeKnora_internal_types.MCPAuthConfig(
                    api_key = '', 
                    custom_headers = {
                        'key' : ''
                        }, 
                    token = '', ),
                created_at = '',
                deleted_at = weknora.models.gorm/deleted_at.gorm.DeletedAt(
                    time = '', 
                    valid = True, ),
                description = '',
                enabled = True,
                env_vars = {
                    'key' : ''
                    },
                headers = {
                    'key' : ''
                    },
                id = '',
                name = '',
                stdio_config = weknora.models.github_com_tencent_we_knora_internal_types/mcp_stdio_config.github_com_Tencent_WeKnora_internal_types.MCPStdioConfig(
                    args = [
                        ''
                        ], 
                    command = '', ),
                tenant_id = 56,
                transport_type = 'sse',
                updated_at = '',
                url = ''
            )
        else:
            return GithubComTencentWeKnoraInternalTypesMCPService(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesMCPService(self):
        """Test GithubComTencentWeKnoraInternalTypesMCPService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
