# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_text_relation_extraction_request import InternalHandlerTextRelationExtractionRequest

class TestInternalHandlerTextRelationExtractionRequest(unittest.TestCase):
    """InternalHandlerTextRelationExtractionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerTextRelationExtractionRequest:
        """Test InternalHandlerTextRelationExtractionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerTextRelationExtractionRequest`
        """
        model = InternalHandlerTextRelationExtractionRequest()
        if include_optional:
            return InternalHandlerTextRelationExtractionRequest(
                llm_config = weknora.models.internal_handler/llm_config.internal_handler.LLMConfig(
                    api_key = '', 
                    base_url = '', 
                    model_name = '', 
                    source = '', ),
                tags = [
                    ''
                    ],
                text = ''
            )
        else:
            return InternalHandlerTextRelationExtractionRequest(
                tags = [
                    ''
                    ],
                text = '',
        )
        """

    def testInternalHandlerTextRelationExtractionRequest(self):
        """Test InternalHandlerTextRelationExtractionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
