# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_register_request import GithubComTencentWeKnoraInternalTypesRegisterRequest

class TestGithubComTencentWeKnoraInternalTypesRegisterRequest(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesRegisterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesRegisterRequest:
        """Test GithubComTencentWeKnoraInternalTypesRegisterRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesRegisterRequest`
        """
        model = GithubComTencentWeKnoraInternalTypesRegisterRequest()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesRegisterRequest(
                email = '',
                password = '012345',
                username = '012'
            )
        else:
            return GithubComTencentWeKnoraInternalTypesRegisterRequest(
                email = '',
                password = '012345',
                username = '012',
        )
        """

    def testGithubComTencentWeKnoraInternalTypesRegisterRequest(self):
        """Test GithubComTencentWeKnoraInternalTypesRegisterRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
