# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.knowledge_bases_id_tags_post_request import KnowledgeBasesIdTagsPostRequest

class TestKnowledgeBasesIdTagsPostRequest(unittest.TestCase):
    """KnowledgeBasesIdTagsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KnowledgeBasesIdTagsPostRequest:
        """Test KnowledgeBasesIdTagsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KnowledgeBasesIdTagsPostRequest`
        """
        model = KnowledgeBasesIdTagsPostRequest()
        if include_optional:
            return KnowledgeBasesIdTagsPostRequest(
                color = '',
                name = '',
                sort_order = 56
            )
        else:
            return KnowledgeBasesIdTagsPostRequest(
        )
        """

    def testKnowledgeBasesIdTagsPostRequest(self):
        """Test KnowledgeBasesIdTagsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
