# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.auth_change_password_post_request import AuthChangePasswordPostRequest

class TestAuthChangePasswordPostRequest(unittest.TestCase):
    """AuthChangePasswordPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthChangePasswordPostRequest:
        """Test AuthChangePasswordPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthChangePasswordPostRequest`
        """
        model = AuthChangePasswordPostRequest()
        if include_optional:
            return AuthChangePasswordPostRequest(
                new_password = '',
                old_password = ''
            )
        else:
            return AuthChangePasswordPostRequest(
        )
        """

    def testAuthChangePasswordPostRequest(self):
        """Test AuthChangePasswordPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
