# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_kb_model_config_request_node_extract import InternalHandlerKBModelConfigRequestNodeExtract

class TestInternalHandlerKBModelConfigRequestNodeExtract(unittest.TestCase):
    """InternalHandlerKBModelConfigRequestNodeExtract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerKBModelConfigRequestNodeExtract:
        """Test InternalHandlerKBModelConfigRequestNodeExtract
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerKBModelConfigRequestNodeExtract`
        """
        model = InternalHandlerKBModelConfigRequestNodeExtract()
        if include_optional:
            return InternalHandlerKBModelConfigRequestNodeExtract(
                enabled = True,
                nodes = [
                    weknora.models.github_com_tencent_we_knora_internal_types/graph_node.github_com_Tencent_WeKnora_internal_types.GraphNode(
                        attributes = [
                            ''
                            ], 
                        chunks = [
                            ''
                            ], 
                        name = '', )
                    ],
                relations = [
                    weknora.models.github_com_tencent_we_knora_internal_types/graph_relation.github_com_Tencent_WeKnora_internal_types.GraphRelation(
                        node1 = '', 
                        node2 = '', 
                        type = '', )
                    ],
                tags = [
                    ''
                    ],
                text = ''
            )
        else:
            return InternalHandlerKBModelConfigRequestNodeExtract(
        )
        """

    def testInternalHandlerKBModelConfigRequestNodeExtract(self):
        """Test InternalHandlerKBModelConfigRequestNodeExtract"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
