# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_faq_entry_payload import GithubComTencentWeKnoraInternalTypesFAQEntryPayload

class TestGithubComTencentWeKnoraInternalTypesFAQEntryPayload(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesFAQEntryPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesFAQEntryPayload:
        """Test GithubComTencentWeKnoraInternalTypesFAQEntryPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesFAQEntryPayload`
        """
        model = GithubComTencentWeKnoraInternalTypesFAQEntryPayload()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesFAQEntryPayload(
                answer_strategy = 'all',
                answers = [
                    ''
                    ],
                is_enabled = True,
                is_recommended = True,
                negative_questions = [
                    ''
                    ],
                similar_questions = [
                    ''
                    ],
                standard_question = '',
                tag_id = '',
                tag_name = ''
            )
        else:
            return GithubComTencentWeKnoraInternalTypesFAQEntryPayload(
                answers = [
                    ''
                    ],
                standard_question = '',
        )
        """

    def testGithubComTencentWeKnoraInternalTypesFAQEntryPayload(self):
        """Test GithubComTencentWeKnoraInternalTypesFAQEntryPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
