# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.knowledge_bases_id_knowledge_url_post_request import KnowledgeBasesIdKnowledgeUrlPostRequest

class TestKnowledgeBasesIdKnowledgeUrlPostRequest(unittest.TestCase):
    """KnowledgeBasesIdKnowledgeUrlPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KnowledgeBasesIdKnowledgeUrlPostRequest:
        """Test KnowledgeBasesIdKnowledgeUrlPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KnowledgeBasesIdKnowledgeUrlPostRequest`
        """
        model = KnowledgeBasesIdKnowledgeUrlPostRequest()
        if include_optional:
            return KnowledgeBasesIdKnowledgeUrlPostRequest(
                enable_multimodel = True,
                title = '',
                url = ''
            )
        else:
            return KnowledgeBasesIdKnowledgeUrlPostRequest(
        )
        """

    def testKnowledgeBasesIdKnowledgeUrlPostRequest(self):
        """Test KnowledgeBasesIdKnowledgeUrlPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
