# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_session_create_session_request import InternalHandlerSessionCreateSessionRequest

class TestInternalHandlerSessionCreateSessionRequest(unittest.TestCase):
    """InternalHandlerSessionCreateSessionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerSessionCreateSessionRequest:
        """Test InternalHandlerSessionCreateSessionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerSessionCreateSessionRequest`
        """
        model = InternalHandlerSessionCreateSessionRequest()
        if include_optional:
            return InternalHandlerSessionCreateSessionRequest(
                agent_config = weknora.models.github_com_tencent_we_knora_internal_types/session_agent_config.github_com_Tencent_WeKnora_internal_types.SessionAgentConfig(
                    agent_mode_enabled = True, 
                    knowledge_bases = [
                        ''
                        ], 
                    knowledge_ids = [
                        ''
                        ], 
                    web_search_enabled = True, ),
                knowledge_base_id = '',
                session_strategy = weknora.models.internal_handler_session/session_strategy.internal_handler_session.SessionStrategy(
                    embedding_top_k = 56, 
                    enable_rewrite = True, 
                    fallback_response = '', 
                    fallback_strategy = weknora.models.fallback_strategy.fallback_strategy(), 
                    keyword_threshold = 1.337, 
                    max_rounds = 56, 
                    no_match_prefix = '', 
                    rerank_model_id = '', 
                    rerank_threshold = 1.337, 
                    rerank_top_k = 56, 
                    summary_model_id = '', 
                    summary_parameters = weknora.models.summary_parameters.summary_parameters(), 
                    vector_threshold = 1.337, )
            )
        else:
            return InternalHandlerSessionCreateSessionRequest(
        )
        """

    def testInternalHandlerSessionCreateSessionRequest(self):
        """Test InternalHandlerSessionCreateSessionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
