# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_session_mentioned_item_request import InternalHandlerSessionMentionedItemRequest

class TestInternalHandlerSessionMentionedItemRequest(unittest.TestCase):
    """InternalHandlerSessionMentionedItemRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerSessionMentionedItemRequest:
        """Test InternalHandlerSessionMentionedItemRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerSessionMentionedItemRequest`
        """
        model = InternalHandlerSessionMentionedItemRequest()
        if include_optional:
            return InternalHandlerSessionMentionedItemRequest(
                id = '',
                kb_type = '',
                name = '',
                type = ''
            )
        else:
            return InternalHandlerSessionMentionedItemRequest(
        )
        """

    def testInternalHandlerSessionMentionedItemRequest(self):
        """Test InternalHandlerSessionMentionedItemRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
