# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_knowledge_base_config import GithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig

class TestGithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig:
        """Test GithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig`
        """
        model = GithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig(
                chunking_config = weknora.models.github_com_tencent_we_knora_internal_types/chunking_config.github_com_Tencent_WeKnora_internal_types.ChunkingConfig(
                    chunk_overlap = 56, 
                    chunk_size = 56, 
                    enable_multimodal = True, 
                    separators = [
                        ''
                        ], ),
                faq_config = weknora.models.github_com_tencent_we_knora_internal_types/faq_config.github_com_Tencent_WeKnora_internal_types.FAQConfig(
                    index_mode = 'question_only', 
                    question_index_mode = 'combined', ),
                image_processing_config = weknora.models.github_com_tencent_we_knora_internal_types/image_processing_config.github_com_Tencent_WeKnora_internal_types.ImageProcessingConfig(
                    model_id = '', )
            )
        else:
            return GithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig(self):
        """Test GithubComTencentWeKnoraInternalTypesKnowledgeBaseConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
