# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_context_compression_strategy import GithubComTencentWeKnoraInternalTypesContextCompressionStrategy

class TestGithubComTencentWeKnoraInternalTypesContextCompressionStrategy(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesContextCompressionStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGithubComTencentWeKnoraInternalTypesContextCompressionStrategy(self):
        """Test GithubComTencentWeKnoraInternalTypesContextCompressionStrategy"""
        # inst = GithubComTencentWeKnoraInternalTypesContextCompressionStrategy()

if __name__ == '__main__':
    unittest.main()
