# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.api.web_search_api import WebSearchApi


class TestWebSearchApi(unittest.TestCase):
    """WebSearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebSearchApi()

    def tearDown(self) -> None:
        pass

    def test_web_search_providers_get(self) -> None:
        """Test case for web_search_providers_get

        Get available web search providers
        """
        pass


if __name__ == '__main__':
    unittest.main()
