# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_kb_model_config_request_document_splitting import InternalHandlerKBModelConfigRequestDocumentSplitting

class TestInternalHandlerKBModelConfigRequestDocumentSplitting(unittest.TestCase):
    """InternalHandlerKBModelConfigRequestDocumentSplitting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerKBModelConfigRequestDocumentSplitting:
        """Test InternalHandlerKBModelConfigRequestDocumentSplitting
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerKBModelConfigRequestDocumentSplitting`
        """
        model = InternalHandlerKBModelConfigRequestDocumentSplitting()
        if include_optional:
            return InternalHandlerKBModelConfigRequestDocumentSplitting(
                chunk_overlap = 56,
                chunk_size = 56,
                separators = [
                    ''
                    ]
            )
        else:
            return InternalHandlerKBModelConfigRequestDocumentSplitting(
        )
        """

    def testInternalHandlerKBModelConfigRequestDocumentSplitting(self):
        """Test InternalHandlerKBModelConfigRequestDocumentSplitting"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
