# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_faq_batch_upsert_payload import GithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload

class TestGithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload:
        """Test GithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload`
        """
        model = GithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload(
                entries = [
                    weknora.models.github_com_tencent_we_knora_internal_types/faq_entry_payload.github_com_Tencent_WeKnora_internal_types.FAQEntryPayload(
                        answer_strategy = 'all', 
                        answers = [
                            ''
                            ], 
                        is_enabled = True, 
                        is_recommended = True, 
                        negative_questions = [
                            ''
                            ], 
                        similar_questions = [
                            ''
                            ], 
                        standard_question = '', 
                        tag_id = '', 
                        tag_name = '', )
                    ],
                knowledge_id = '',
                mode = 'append'
            )
        else:
            return GithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload(
                entries = [
                    weknora.models.github_com_tencent_we_knora_internal_types/faq_entry_payload.github_com_Tencent_WeKnora_internal_types.FAQEntryPayload(
                        answer_strategy = 'all', 
                        answers = [
                            ''
                            ], 
                        is_enabled = True, 
                        is_recommended = True, 
                        negative_questions = [
                            ''
                            ], 
                        similar_questions = [
                            ''
                            ], 
                        standard_question = '', 
                        tag_id = '', 
                        tag_name = '', )
                    ],
        )
        """

    def testGithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload(self):
        """Test GithubComTencentWeKnoraInternalTypesFAQBatchUpsertPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
