# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.api.faq_api import FAQApi


class TestFAQApi(unittest.TestCase):
    """FAQApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FAQApi()

    def tearDown(self) -> None:
        pass

    def test_faq_import_progress_task_id_get(self) -> None:
        """Test case for faq_import_progress_task_id_get

        获取FAQ导入进度
        """
        pass

    def test_knowledge_bases_id_faq_entries_delete(self) -> None:
        """Test case for knowledge_bases_id_faq_entries_delete

        批量删除FAQ条目
        """
        pass

    def test_knowledge_bases_id_faq_entries_entry_id_get(self) -> None:
        """Test case for knowledge_bases_id_faq_entries_entry_id_get

        获取FAQ条目详情
        """
        pass

    def test_knowledge_bases_id_faq_entries_entry_id_put(self) -> None:
        """Test case for knowledge_bases_id_faq_entries_entry_id_put

        更新FAQ条目
        """
        pass

    def test_knowledge_bases_id_faq_entries_export_get(self) -> None:
        """Test case for knowledge_bases_id_faq_entries_export_get

        导出FAQ条目
        """
        pass

    def test_knowledge_bases_id_faq_entries_fields_put(self) -> None:
        """Test case for knowledge_bases_id_faq_entries_fields_put

        批量更新FAQ字段
        """
        pass

    def test_knowledge_bases_id_faq_entries_get(self) -> None:
        """Test case for knowledge_bases_id_faq_entries_get

        获取FAQ条目列表
        """
        pass

    def test_knowledge_bases_id_faq_entries_post(self) -> None:
        """Test case for knowledge_bases_id_faq_entries_post

        批量更新/插入FAQ条目
        """
        pass

    def test_knowledge_bases_id_faq_entries_tags_put(self) -> None:
        """Test case for knowledge_bases_id_faq_entries_tags_put

        批量更新FAQ标签
        """
        pass

    def test_knowledge_bases_id_faq_entry_post(self) -> None:
        """Test case for knowledge_bases_id_faq_entry_post

        创建单个FAQ条目
        """
        pass

    def test_knowledge_bases_id_faq_search_post(self) -> None:
        """Test case for knowledge_bases_id_faq_search_post

        搜索FAQ
        """
        pass


if __name__ == '__main__':
    unittest.main()
