# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_auth_change_password_post(self) -> None:
        """Test case for auth_change_password_post

        修改密码
        """
        pass

    def test_auth_login_post(self) -> None:
        """Test case for auth_login_post

        用户登录
        """
        pass

    def test_auth_logout_post(self) -> None:
        """Test case for auth_logout_post

        用户登出
        """
        pass

    def test_auth_me_get(self) -> None:
        """Test case for auth_me_get

        获取当前用户信息
        """
        pass

    def test_auth_refresh_post(self) -> None:
        """Test case for auth_refresh_post

        刷新令牌
        """
        pass

    def test_auth_register_post(self) -> None:
        """Test case for auth_register_post

        用户注册
        """
        pass

    def test_auth_validate_get(self) -> None:
        """Test case for auth_validate_get

        验证令牌
        """
        pass

    def test_chunks_by_id_id_get(self) -> None:
        """Test case for chunks_by_id_id_get

        通过ID获取分块
        """
        pass

    def test_chunks_by_id_id_questions_delete(self) -> None:
        """Test case for chunks_by_id_id_questions_delete

        删除生成的问题
        """
        pass

    def test_chunks_knowledge_id_delete(self) -> None:
        """Test case for chunks_knowledge_id_delete

        删除知识下所有分块
        """
        pass

    def test_chunks_knowledge_id_get(self) -> None:
        """Test case for chunks_knowledge_id_get

        获取知识分块列表
        """
        pass

    def test_chunks_knowledge_id_id_delete(self) -> None:
        """Test case for chunks_knowledge_id_id_delete

        删除分块
        """
        pass

    def test_chunks_knowledge_id_id_put(self) -> None:
        """Test case for chunks_knowledge_id_id_put

        更新分块
        """
        pass

    def test_evaluation_get(self) -> None:
        """Test case for evaluation_get

        获取评估结果
        """
        pass

    def test_evaluation_post(self) -> None:
        """Test case for evaluation_post

        执行评估
        """
        pass

    def test_initialization_extract_relations_post(self) -> None:
        """Test case for initialization_extract_relations_post

        提取文本关系
        """
        pass

    def test_initialization_fabri_tag_get(self) -> None:
        """Test case for initialization_fabri_tag_get

        生成随机标签
        """
        pass

    def test_initialization_fabri_text_post(self) -> None:
        """Test case for initialization_fabri_text_post

        生成示例文本
        """
        pass

    def test_initialization_kb_kb_id_config_get(self) -> None:
        """Test case for initialization_kb_kb_id_config_get

        获取知识库配置
        """
        pass

    def test_initialization_kb_kb_id_config_put(self) -> None:
        """Test case for initialization_kb_kb_id_config_put

        更新知识库配置
        """
        pass

    def test_initialization_kb_kb_id_post(self) -> None:
        """Test case for initialization_kb_kb_id_post

        初始化知识库配置
        """
        pass

    def test_initialization_models_embedding_test_post(self) -> None:
        """Test case for initialization_models_embedding_test_post

        测试Embedding模型
        """
        pass

    def test_initialization_models_remote_check_post(self) -> None:
        """Test case for initialization_models_remote_check_post

        检查远程模型
        """
        pass

    def test_initialization_models_rerank_check_post(self) -> None:
        """Test case for initialization_models_rerank_check_post

        检查Rerank模型
        """
        pass

    def test_initialization_multimodal_test_post(self) -> None:
        """Test case for initialization_multimodal_test_post

        测试多模态功能
        """
        pass

    def test_initialization_ollama_download_task_id_get(self) -> None:
        """Test case for initialization_ollama_download_task_id_get

        获取下载进度
        """
        pass

    def test_initialization_ollama_download_tasks_get(self) -> None:
        """Test case for initialization_ollama_download_tasks_get

        列出下载任务
        """
        pass

    def test_initialization_ollama_models_check_post(self) -> None:
        """Test case for initialization_ollama_models_check_post

        检查Ollama模型状态
        """
        pass

    def test_initialization_ollama_models_download_post(self) -> None:
        """Test case for initialization_ollama_models_download_post

        下载Ollama模型
        """
        pass

    def test_initialization_ollama_models_get(self) -> None:
        """Test case for initialization_ollama_models_get

        列出Ollama模型
        """
        pass

    def test_initialization_ollama_status_get(self) -> None:
        """Test case for initialization_ollama_status_get

        检查Ollama服务状态
        """
        pass

    def test_knowledge_bases_copy_post(self) -> None:
        """Test case for knowledge_bases_copy_post

        复制知识库
        """
        pass

    def test_knowledge_bases_copy_progress_task_id_get(self) -> None:
        """Test case for knowledge_bases_copy_progress_task_id_get

        获取知识库复制进度
        """
        pass

    def test_knowledge_bases_get(self) -> None:
        """Test case for knowledge_bases_get

        获取知识库列表
        """
        pass

    def test_knowledge_bases_id_delete(self) -> None:
        """Test case for knowledge_bases_id_delete

        删除知识库
        """
        pass

    def test_knowledge_bases_id_get(self) -> None:
        """Test case for knowledge_bases_id_get

        获取知识库详情
        """
        pass

    def test_knowledge_bases_id_hybrid_search_get(self) -> None:
        """Test case for knowledge_bases_id_hybrid_search_get

        混合搜索
        """
        pass

    def test_knowledge_bases_id_knowledge_file_post(self) -> None:
        """Test case for knowledge_bases_id_knowledge_file_post

        从文件创建知识
        """
        pass

    def test_knowledge_bases_id_knowledge_get(self) -> None:
        """Test case for knowledge_bases_id_knowledge_get

        获取知识列表
        """
        pass

    def test_knowledge_bases_id_knowledge_manual_post(self) -> None:
        """Test case for knowledge_bases_id_knowledge_manual_post

        手工创建知识
        """
        pass

    def test_knowledge_bases_id_knowledge_url_post(self) -> None:
        """Test case for knowledge_bases_id_knowledge_url_post

        从URL创建知识
        """
        pass

    def test_knowledge_bases_id_put(self) -> None:
        """Test case for knowledge_bases_id_put

        更新知识库
        """
        pass

    def test_knowledge_bases_id_tags_get(self) -> None:
        """Test case for knowledge_bases_id_tags_get

        获取标签列表
        """
        pass

    def test_knowledge_bases_id_tags_post(self) -> None:
        """Test case for knowledge_bases_id_tags_post

        创建标签
        """
        pass

    def test_knowledge_bases_id_tags_tag_id_delete(self) -> None:
        """Test case for knowledge_bases_id_tags_tag_id_delete

        删除标签
        """
        pass

    def test_knowledge_bases_id_tags_tag_id_put(self) -> None:
        """Test case for knowledge_bases_id_tags_tag_id_put

        更新标签
        """
        pass

    def test_knowledge_bases_post(self) -> None:
        """Test case for knowledge_bases_post

        创建知识库
        """
        pass

    def test_knowledge_batch_get(self) -> None:
        """Test case for knowledge_batch_get

        批量获取知识
        """
        pass

    def test_knowledge_id_delete(self) -> None:
        """Test case for knowledge_id_delete

        删除知识
        """
        pass

    def test_knowledge_id_download_get(self) -> None:
        """Test case for knowledge_id_download_get

        下载知识文件
        """
        pass

    def test_knowledge_id_get(self) -> None:
        """Test case for knowledge_id_get

        获取知识详情
        """
        pass

    def test_knowledge_id_put(self) -> None:
        """Test case for knowledge_id_put

        更新知识
        """
        pass

    def test_knowledge_image_id_chunk_id_put(self) -> None:
        """Test case for knowledge_image_id_chunk_id_put

        更新图像信息
        """
        pass

    def test_knowledge_manual_id_put(self) -> None:
        """Test case for knowledge_manual_id_put

        更新手工知识
        """
        pass

    def test_knowledge_tags_put(self) -> None:
        """Test case for knowledge_tags_put

        批量更新知识标签
        """
        pass

    def test_messages_session_id_id_delete(self) -> None:
        """Test case for messages_session_id_id_delete

        删除消息
        """
        pass

    def test_messages_session_id_load_get(self) -> None:
        """Test case for messages_session_id_load_get

        加载消息历史
        """
        pass

    def test_models_get(self) -> None:
        """Test case for models_get

        获取模型列表
        """
        pass

    def test_models_id_delete(self) -> None:
        """Test case for models_id_delete

        删除模型
        """
        pass

    def test_models_id_get(self) -> None:
        """Test case for models_id_get

        获取模型详情
        """
        pass

    def test_models_id_put(self) -> None:
        """Test case for models_id_put

        更新模型
        """
        pass

    def test_models_post(self) -> None:
        """Test case for models_post

        创建模型
        """
        pass

    def test_sessions_get(self) -> None:
        """Test case for sessions_get

        获取会话列表
        """
        pass

    def test_sessions_id_delete(self) -> None:
        """Test case for sessions_id_delete

        删除会话
        """
        pass

    def test_sessions_id_get(self) -> None:
        """Test case for sessions_id_get

        获取会话详情
        """
        pass

    def test_sessions_id_put(self) -> None:
        """Test case for sessions_id_put

        更新会话
        """
        pass

    def test_sessions_post(self) -> None:
        """Test case for sessions_post

        创建会话
        """
        pass

    def test_sessions_search_post(self) -> None:
        """Test case for sessions_search_post

        知识搜索
        """
        pass

    def test_sessions_session_id_agent_qa_post(self) -> None:
        """Test case for sessions_session_id_agent_qa_post

        Agent问答
        """
        pass

    def test_sessions_session_id_continue_get(self) -> None:
        """Test case for sessions_session_id_continue_get

        继续流式响应
        """
        pass

    def test_sessions_session_id_knowledge_qa_post(self) -> None:
        """Test case for sessions_session_id_knowledge_qa_post

        知识问答
        """
        pass

    def test_sessions_session_id_stop_post(self) -> None:
        """Test case for sessions_session_id_stop_post

        停止生成
        """
        pass

    def test_sessions_session_id_title_post(self) -> None:
        """Test case for sessions_session_id_title_post

        生成会话标题
        """
        pass

    def test_system_info_get(self) -> None:
        """Test case for system_info_get

        获取系统信息
        """
        pass

    def test_tenants_all_get(self) -> None:
        """Test case for tenants_all_get

        获取所有租户列表
        """
        pass

    def test_tenants_get(self) -> None:
        """Test case for tenants_get

        获取租户列表
        """
        pass

    def test_tenants_id_delete(self) -> None:
        """Test case for tenants_id_delete

        删除租户
        """
        pass

    def test_tenants_id_get(self) -> None:
        """Test case for tenants_id_get

        获取租户详情
        """
        pass

    def test_tenants_id_put(self) -> None:
        """Test case for tenants_id_put

        更新租户
        """
        pass

    def test_tenants_kv_agent_config_get(self) -> None:
        """Test case for tenants_kv_agent_config_get

        获取租户Agent配置
        """
        pass

    def test_tenants_kv_conversation_config_get(self) -> None:
        """Test case for tenants_kv_conversation_config_get

        获取租户对话配置
        """
        pass

    def test_tenants_kv_key_get(self) -> None:
        """Test case for tenants_kv_key_get

        获取租户KV配置
        """
        pass

    def test_tenants_kv_key_put(self) -> None:
        """Test case for tenants_kv_key_put

        更新租户KV配置
        """
        pass

    def test_tenants_kv_web_search_config_get(self) -> None:
        """Test case for tenants_kv_web_search_config_get

        获取租户网络搜索配置
        """
        pass

    def test_tenants_post(self) -> None:
        """Test case for tenants_post

        创建租户
        """
        pass

    def test_tenants_search_get(self) -> None:
        """Test case for tenants_search_get

        搜索租户
        """
        pass


if __name__ == '__main__':
    unittest.main()
