# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_get_system_info_response import InternalHandlerGetSystemInfoResponse

class TestInternalHandlerGetSystemInfoResponse(unittest.TestCase):
    """InternalHandlerGetSystemInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerGetSystemInfoResponse:
        """Test InternalHandlerGetSystemInfoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerGetSystemInfoResponse`
        """
        model = InternalHandlerGetSystemInfoResponse()
        if include_optional:
            return InternalHandlerGetSystemInfoResponse(
                build_time = '',
                commit_id = '',
                go_version = '',
                graph_database_engine = '',
                keyword_index_engine = '',
                minio_enabled = True,
                vector_store_engine = '',
                version = ''
            )
        else:
            return InternalHandlerGetSystemInfoResponse(
        )
        """

    def testInternalHandlerGetSystemInfoResponse(self):
        """Test InternalHandlerGetSystemInfoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
