# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_retriever_type import GithubComTencentWeKnoraInternalTypesRetrieverType

class TestGithubComTencentWeKnoraInternalTypesRetrieverType(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesRetrieverType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGithubComTencentWeKnoraInternalTypesRetrieverType(self):
        """Test GithubComTencentWeKnoraInternalTypesRetrieverType"""
        # inst = GithubComTencentWeKnoraInternalTypesRetrieverType()

if __name__ == '__main__':
    unittest.main()
