# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_session_session_strategy import InternalHandlerSessionSessionStrategy

class TestInternalHandlerSessionSessionStrategy(unittest.TestCase):
    """InternalHandlerSessionSessionStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerSessionSessionStrategy:
        """Test InternalHandlerSessionSessionStrategy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerSessionSessionStrategy`
        """
        model = InternalHandlerSessionSessionStrategy()
        if include_optional:
            return InternalHandlerSessionSessionStrategy(
                embedding_top_k = 56,
                enable_rewrite = True,
                fallback_response = '',
                fallback_strategy = 'fixed',
                keyword_threshold = 1.337,
                max_rounds = 56,
                no_match_prefix = '',
                rerank_model_id = '',
                rerank_threshold = 1.337,
                rerank_top_k = 56,
                summary_model_id = '',
                summary_parameters = weknora.models.github_com_tencent_we_knora_internal_types/summary_config.github_com_Tencent_WeKnora_internal_types.SummaryConfig(
                    context_template = '', 
                    frequency_penalty = 1.337, 
                    max_completion_tokens = 56, 
                    max_tokens = 56, 
                    no_match_prefix = '', 
                    presence_penalty = 1.337, 
                    prompt = '', 
                    repeat_penalty = 1.337, 
                    seed = 56, 
                    temperature = 1.337, 
                    top_k = 56, 
                    top_p = 1.337, ),
                vector_threshold = 1.337
            )
        else:
            return InternalHandlerSessionSessionStrategy(
        )
        """

    def testInternalHandlerSessionSessionStrategy(self):
        """Test InternalHandlerSessionSessionStrategy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
