# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_kb_model_config_request_multimodal import InternalHandlerKBModelConfigRequestMultimodal

class TestInternalHandlerKBModelConfigRequestMultimodal(unittest.TestCase):
    """InternalHandlerKBModelConfigRequestMultimodal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerKBModelConfigRequestMultimodal:
        """Test InternalHandlerKBModelConfigRequestMultimodal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerKBModelConfigRequestMultimodal`
        """
        model = InternalHandlerKBModelConfigRequestMultimodal()
        if include_optional:
            return InternalHandlerKBModelConfigRequestMultimodal(
                cos = weknora.models.internal_handler_kb_model_config_request_multimodal_cos.internal_handler_KBModelConfigRequest_multimodal_cos(
                    app_id = '', 
                    bucket_name = '', 
                    path_prefix = '', 
                    region = '', 
                    secret_id = '', 
                    secret_key = '', ),
                enabled = True,
                minio = weknora.models.internal_handler_kb_model_config_request_multimodal_minio.internal_handler_KBModelConfigRequest_multimodal_minio(
                    bucket_name = '', 
                    path_prefix = '', 
                    use_ssl = True, ),
                storage_type = ''
            )
        else:
            return InternalHandlerKBModelConfigRequestMultimodal(
        )
        """

    def testInternalHandlerKBModelConfigRequestMultimodal(self):
        """Test InternalHandlerKBModelConfigRequestMultimodal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
