# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_session_search_knowledge_request import InternalHandlerSessionSearchKnowledgeRequest

class TestInternalHandlerSessionSearchKnowledgeRequest(unittest.TestCase):
    """InternalHandlerSessionSearchKnowledgeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerSessionSearchKnowledgeRequest:
        """Test InternalHandlerSessionSearchKnowledgeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerSessionSearchKnowledgeRequest`
        """
        model = InternalHandlerSessionSearchKnowledgeRequest()
        if include_optional:
            return InternalHandlerSessionSearchKnowledgeRequest(
                knowledge_base_id = '',
                knowledge_base_ids = [
                    ''
                    ],
                knowledge_ids = [
                    ''
                    ],
                query = ''
            )
        else:
            return InternalHandlerSessionSearchKnowledgeRequest(
                query = '',
        )
        """

    def testInternalHandlerSessionSearchKnowledgeRequest(self):
        """Test InternalHandlerSessionSearchKnowledgeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
