# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.api.mcp_api import MCPApi


class TestMCPApi(unittest.TestCase):
    """MCPApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MCPApi()

    def tearDown(self) -> None:
        pass

    def test_mcp_services_get(self) -> None:
        """Test case for mcp_services_get

        获取MCP服务列表
        """
        pass

    def test_mcp_services_id_delete(self) -> None:
        """Test case for mcp_services_id_delete

        删除MCP服务
        """
        pass

    def test_mcp_services_id_get(self) -> None:
        """Test case for mcp_services_id_get

        获取MCP服务详情
        """
        pass

    def test_mcp_services_id_put(self) -> None:
        """Test case for mcp_services_id_put

        更新MCP服务
        """
        pass

    def test_mcp_services_id_resources_get(self) -> None:
        """Test case for mcp_services_id_resources_get

        获取MCP服务资源列表
        """
        pass

    def test_mcp_services_id_test_post(self) -> None:
        """Test case for mcp_services_id_test_post

        测试MCP服务连接
        """
        pass

    def test_mcp_services_id_tools_get(self) -> None:
        """Test case for mcp_services_id_tools_get

        获取MCP服务工具列表
        """
        pass

    def test_mcp_services_post(self) -> None:
        """Test case for mcp_services_post

        创建MCP服务
        """
        pass


if __name__ == '__main__':
    unittest.main()
