# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_conversation_config import GithubComTencentWeKnoraInternalTypesConversationConfig

class TestGithubComTencentWeKnoraInternalTypesConversationConfig(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesConversationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesConversationConfig:
        """Test GithubComTencentWeKnoraInternalTypesConversationConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesConversationConfig`
        """
        model = GithubComTencentWeKnoraInternalTypesConversationConfig()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesConversationConfig(
                context_template = '',
                embedding_top_k = 56,
                enable_query_expansion = True,
                enable_rewrite = True,
                fallback_prompt = '',
                fallback_response = '',
                fallback_strategy = '',
                keyword_threshold = 1.337,
                max_completion_tokens = 56,
                max_rounds = 56,
                prompt = '',
                rerank_model_id = '',
                rerank_threshold = 1.337,
                rerank_top_k = 56,
                rewrite_prompt_system = '',
                rewrite_prompt_user = '',
                summary_model_id = '',
                temperature = 1.337,
                use_custom_context_template = True,
                use_custom_system_prompt = True,
                vector_threshold = 1.337
            )
        else:
            return GithubComTencentWeKnoraInternalTypesConversationConfig(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesConversationConfig(self):
        """Test GithubComTencentWeKnoraInternalTypesConversationConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
