# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_login_response import GithubComTencentWeKnoraInternalTypesLoginResponse

class TestGithubComTencentWeKnoraInternalTypesLoginResponse(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesLoginResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesLoginResponse:
        """Test GithubComTencentWeKnoraInternalTypesLoginResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesLoginResponse`
        """
        model = GithubComTencentWeKnoraInternalTypesLoginResponse()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesLoginResponse(
                message = '',
                refresh_token = '',
                success = True,
                tenant = weknora.models.github_com_tencent_we_knora_internal_types/tenant.github_com_Tencent_WeKnora_internal_types.Tenant(
                    agent_config = weknora.models.agent_config.agent_config(), 
                    api_key = '', 
                    business = '', 
                    context_config = weknora.models.context_config.context_config(), 
                    conversation_config = weknora.models.conversation_config.conversation_config(), 
                    created_at = '', 
                    deleted_at = weknora.models.deleted_at.deleted_at(), 
                    description = '', 
                    id = 56, 
                    name = '', 
                    retriever_engines = weknora.models.retriever_engines.retriever_engines(), 
                    status = '', 
                    storage_quota = 56, 
                    storage_used = 56, 
                    updated_at = '', 
                    web_search_config = weknora.models.web_search_config.web_search_config(), ),
                token = '',
                user = weknora.models.github_com_tencent_we_knora_internal_types/user.github_com_Tencent_WeKnora_internal_types.User(
                    avatar = '', 
                    can_access_all_tenants = True, 
                    created_at = '', 
                    deleted_at = weknora.models.deleted_at.deleted_at(), 
                    email = '', 
                    id = '', 
                    is_active = True, 
                    tenant = weknora.models.tenant.tenant(), 
                    tenant_id = 56, 
                    updated_at = '', 
                    username = '', )
            )
        else:
            return GithubComTencentWeKnoraInternalTypesLoginResponse(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesLoginResponse(self):
        """Test GithubComTencentWeKnoraInternalTypesLoginResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
