# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_kb_model_config_request import InternalHandlerKBModelConfigRequest

class TestInternalHandlerKBModelConfigRequest(unittest.TestCase):
    """InternalHandlerKBModelConfigRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerKBModelConfigRequest:
        """Test InternalHandlerKBModelConfigRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerKBModelConfigRequest`
        """
        model = InternalHandlerKBModelConfigRequest()
        if include_optional:
            return InternalHandlerKBModelConfigRequest(
                document_splitting = weknora.models.internal_handler_kb_model_config_request_document_splitting.internal_handler_KBModelConfigRequest_documentSplitting(
                    chunk_overlap = 56, 
                    chunk_size = 56, 
                    separators = [
                        ''
                        ], ),
                embedding_model_id = '',
                llm_model_id = '',
                multimodal = weknora.models.internal_handler_kb_model_config_request_multimodal.internal_handler_KBModelConfigRequest_multimodal(
                    cos = weknora.models.internal_handler_kb_model_config_request_multimodal_cos.internal_handler_KBModelConfigRequest_multimodal_cos(
                        app_id = '', 
                        bucket_name = '', 
                        path_prefix = '', 
                        region = '', 
                        secret_id = '', 
                        secret_key = '', ), 
                    enabled = True, 
                    minio = weknora.models.internal_handler_kb_model_config_request_multimodal_minio.internal_handler_KBModelConfigRequest_multimodal_minio(
                        bucket_name = '', 
                        path_prefix = '', 
                        use_ssl = True, ), 
                    storage_type = '', ),
                node_extract = weknora.models.internal_handler_kb_model_config_request_node_extract.internal_handler_KBModelConfigRequest_nodeExtract(
                    enabled = True, 
                    nodes = [
                        weknora.models.github_com_tencent_we_knora_internal_types/graph_node.github_com_Tencent_WeKnora_internal_types.GraphNode(
                            attributes = [
                                ''
                                ], 
                            chunks = [
                                ''
                                ], 
                            name = '', )
                        ], 
                    relations = [
                        weknora.models.github_com_tencent_we_knora_internal_types/graph_relation.github_com_Tencent_WeKnora_internal_types.GraphRelation(
                            node1 = '', 
                            node2 = '', 
                            type = '', )
                        ], 
                    tags = [
                        ''
                        ], 
                    text = '', ),
                question_generation = weknora.models.internal_handler_kb_model_config_request_question_generation.internal_handler_KBModelConfigRequest_questionGeneration(
                    enabled = True, 
                    question_count = 56, ),
                vlm_config = weknora.models.github_com_tencent_we_knora_internal_types/vlm_config.github_com_Tencent_WeKnora_internal_types.VLMConfig(
                    api_key = '', 
                    base_url = '', 
                    enabled = True, 
                    interface_type = '', 
                    model_id = '', 
                    model_name = '', )
            )
        else:
            return InternalHandlerKBModelConfigRequest(
                embedding_model_id = '',
                llm_model_id = '',
        )
        """

    def testInternalHandlerKBModelConfigRequest(self):
        """Test InternalHandlerKBModelConfigRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
