# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_session_create_knowledge_qa_request import InternalHandlerSessionCreateKnowledgeQARequest

class TestInternalHandlerSessionCreateKnowledgeQARequest(unittest.TestCase):
    """InternalHandlerSessionCreateKnowledgeQARequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerSessionCreateKnowledgeQARequest:
        """Test InternalHandlerSessionCreateKnowledgeQARequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerSessionCreateKnowledgeQARequest`
        """
        model = InternalHandlerSessionCreateKnowledgeQARequest()
        if include_optional:
            return InternalHandlerSessionCreateKnowledgeQARequest(
                agent_enabled = True,
                knowledge_base_ids = [
                    ''
                    ],
                knowledge_ids = [
                    ''
                    ],
                mentioned_items = [
                    weknora.models.internal_handler_session/mentioned_item_request.internal_handler_session.MentionedItemRequest(
                        id = '', 
                        kb_type = '', 
                        name = '', 
                        type = '', )
                    ],
                query = '',
                summary_model_id = '',
                web_search_enabled = True
            )
        else:
            return InternalHandlerSessionCreateKnowledgeQARequest(
                query = '',
        )
        """

    def testInternalHandlerSessionCreateKnowledgeQARequest(self):
        """Test InternalHandlerSessionCreateKnowledgeQARequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
