# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_knowledge import GithubComTencentWeKnoraInternalTypesKnowledge

class TestGithubComTencentWeKnoraInternalTypesKnowledge(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesKnowledge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesKnowledge:
        """Test GithubComTencentWeKnoraInternalTypesKnowledge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesKnowledge`
        """
        model = GithubComTencentWeKnoraInternalTypesKnowledge()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesKnowledge(
                created_at = '',
                deleted_at = weknora.models.gorm/deleted_at.gorm.DeletedAt(
                    time = '', 
                    valid = True, ),
                description = '',
                embedding_model_id = '',
                enable_status = '',
                error_message = '',
                file_hash = '',
                file_name = '',
                file_path = '',
                file_size = 56,
                file_type = '',
                id = '',
                knowledge_base_id = '',
                knowledge_base_name = '',
                metadata = [
                    56
                    ],
                parse_status = '',
                processed_at = '',
                source = '',
                storage_size = 56,
                summary_status = '',
                tag_id = '',
                tenant_id = 56,
                title = '',
                type = '',
                updated_at = ''
            )
        else:
            return GithubComTencentWeKnoraInternalTypesKnowledge(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesKnowledge(self):
        """Test GithubComTencentWeKnoraInternalTypesKnowledge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
