# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_faq_entry_fields_batch_update import GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate

class TestGithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate:
        """Test GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate`
        """
        model = GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate(
                by_id = {
                    'key' : weknora.models.github_com_tencent_we_knora_internal_types/faq_entry_fields_update.github_com_Tencent_WeKnora_internal_types.FAQEntryFieldsUpdate(
                        is_enabled = True, 
                        is_recommended = True, 
                        tag_id = '', )
                    },
                by_tag = {
                    'key' : weknora.models.github_com_tencent_we_knora_internal_types/faq_entry_fields_update.github_com_Tencent_WeKnora_internal_types.FAQEntryFieldsUpdate(
                        is_enabled = True, 
                        is_recommended = True, 
                        tag_id = '', )
                    }
            )
        else:
            return GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate(self):
        """Test GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
