# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_update_chunk_request import InternalHandlerUpdateChunkRequest

class TestInternalHandlerUpdateChunkRequest(unittest.TestCase):
    """InternalHandlerUpdateChunkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerUpdateChunkRequest:
        """Test InternalHandlerUpdateChunkRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerUpdateChunkRequest`
        """
        model = InternalHandlerUpdateChunkRequest()
        if include_optional:
            return InternalHandlerUpdateChunkRequest(
                chunk_index = 56,
                content = '',
                embedding = [
                    1.337
                    ],
                end_at = 56,
                image_info = '',
                is_enabled = True,
                start_at = 56
            )
        else:
            return InternalHandlerUpdateChunkRequest(
        )
        """

    def testInternalHandlerUpdateChunkRequest(self):
        """Test InternalHandlerUpdateChunkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
