# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_agent_config import GithubComTencentWeKnoraInternalTypesAgentConfig

class TestGithubComTencentWeKnoraInternalTypesAgentConfig(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesAgentConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesAgentConfig:
        """Test GithubComTencentWeKnoraInternalTypesAgentConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesAgentConfig`
        """
        model = GithubComTencentWeKnoraInternalTypesAgentConfig()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesAgentConfig(
                allowed_tools = [
                    ''
                    ],
                knowledge_bases = [
                    ''
                    ],
                knowledge_ids = [
                    ''
                    ],
                max_iterations = 56,
                reflection_enabled = True,
                system_prompt_web_disabled = '',
                system_prompt_web_enabled = '',
                temperature = 1.337,
                use_custom_system_prompt = True,
                web_search_enabled = True,
                web_search_max_results = 56
            )
        else:
            return GithubComTencentWeKnoraInternalTypesAgentConfig(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesAgentConfig(self):
        """Test GithubComTencentWeKnoraInternalTypesAgentConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
