# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_tenant import GithubComTencentWeKnoraInternalTypesTenant

class TestGithubComTencentWeKnoraInternalTypesTenant(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesTenant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesTenant:
        """Test GithubComTencentWeKnoraInternalTypesTenant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesTenant`
        """
        model = GithubComTencentWeKnoraInternalTypesTenant()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesTenant(
                agent_config = weknora.models.github_com_tencent_we_knora_internal_types/agent_config.github_com_Tencent_WeKnora_internal_types.AgentConfig(
                    allowed_tools = [
                        ''
                        ], 
                    knowledge_bases = [
                        ''
                        ], 
                    knowledge_ids = [
                        ''
                        ], 
                    max_iterations = 56, 
                    reflection_enabled = True, 
                    system_prompt_web_disabled = '', 
                    system_prompt_web_enabled = '', 
                    temperature = 1.337, 
                    use_custom_system_prompt = True, 
                    web_search_enabled = True, 
                    web_search_max_results = 56, ),
                api_key = '',
                business = '',
                context_config = weknora.models.github_com_tencent_we_knora_internal_types/context_config.github_com_Tencent_WeKnora_internal_types.ContextConfig(
                    compression_strategy = weknora.models.compression_strategy.compression_strategy(), 
                    max_tokens = 56, 
                    recent_message_count = 56, 
                    summarize_threshold = 56, ),
                conversation_config = weknora.models.github_com_tencent_we_knora_internal_types/conversation_config.github_com_Tencent_WeKnora_internal_types.ConversationConfig(
                    context_template = '', 
                    embedding_top_k = 56, 
                    enable_query_expansion = True, 
                    enable_rewrite = True, 
                    fallback_prompt = '', 
                    fallback_response = '', 
                    fallback_strategy = '', 
                    keyword_threshold = 1.337, 
                    max_completion_tokens = 56, 
                    max_rounds = 56, 
                    prompt = '', 
                    rerank_model_id = '', 
                    rerank_threshold = 1.337, 
                    rerank_top_k = 56, 
                    rewrite_prompt_system = '', 
                    rewrite_prompt_user = '', 
                    summary_model_id = '', 
                    temperature = 1.337, 
                    use_custom_context_template = True, 
                    use_custom_system_prompt = True, 
                    vector_threshold = 1.337, ),
                created_at = '',
                deleted_at = weknora.models.gorm/deleted_at.gorm.DeletedAt(
                    time = '', 
                    valid = True, ),
                description = '',
                id = 56,
                name = '',
                retriever_engines = weknora.models.github_com_tencent_we_knora_internal_types/retriever_engines.github_com_Tencent_WeKnora_internal_types.RetrieverEngines(
                    engines = [
                        weknora.models.github_com_tencent_we_knora_internal_types/retriever_engine_params.github_com_Tencent_WeKnora_internal_types.RetrieverEngineParams(
                            retriever_engine_type = weknora.models.retriever_engine_type.retriever_engine_type(), 
                            retriever_type = weknora.models.retriever_type.retriever_type(), )
                        ], ),
                status = '',
                storage_quota = 56,
                storage_used = 56,
                updated_at = '',
                web_search_config = weknora.models.github_com_tencent_we_knora_internal_types/web_search_config.github_com_Tencent_WeKnora_internal_types.WebSearchConfig(
                    api_key = '', 
                    blacklist = [
                        ''
                        ], 
                    compression_method = '', 
                    document_fragments = 56, 
                    embedding_dimension = 56, 
                    embedding_model_id = '', 
                    include_date = True, 
                    max_results = 56, 
                    provider = '', 
                    rerank_model_id = '', )
            )
        else:
            return GithubComTencentWeKnoraInternalTypesTenant(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesTenant(self):
        """Test GithubComTencentWeKnoraInternalTypesTenant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
