# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_update_knowledge_base_request import InternalHandlerUpdateKnowledgeBaseRequest

class TestInternalHandlerUpdateKnowledgeBaseRequest(unittest.TestCase):
    """InternalHandlerUpdateKnowledgeBaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerUpdateKnowledgeBaseRequest:
        """Test InternalHandlerUpdateKnowledgeBaseRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerUpdateKnowledgeBaseRequest`
        """
        model = InternalHandlerUpdateKnowledgeBaseRequest()
        if include_optional:
            return InternalHandlerUpdateKnowledgeBaseRequest(
                config = weknora.models.github_com_tencent_we_knora_internal_types/knowledge_base_config.github_com_Tencent_WeKnora_internal_types.KnowledgeBaseConfig(
                    chunking_config = weknora.models.chunking_config.chunking_config(), 
                    faq_config = weknora.models.faq_config.faq_config(), 
                    image_processing_config = weknora.models.image_processing_config.image_processing_config(), ),
                description = '',
                name = ''
            )
        else:
            return InternalHandlerUpdateKnowledgeBaseRequest(
                config = weknora.models.github_com_tencent_we_knora_internal_types/knowledge_base_config.github_com_Tencent_WeKnora_internal_types.KnowledgeBaseConfig(
                    chunking_config = weknora.models.chunking_config.chunking_config(), 
                    faq_config = weknora.models.faq_config.faq_config(), 
                    image_processing_config = weknora.models.image_processing_config.image_processing_config(), ),
                name = '',
        )
        """

    def testInternalHandlerUpdateKnowledgeBaseRequest(self):
        """Test InternalHandlerUpdateKnowledgeBaseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
