# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_web_search_config import GithubComTencentWeKnoraInternalTypesWebSearchConfig

class TestGithubComTencentWeKnoraInternalTypesWebSearchConfig(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesWebSearchConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesWebSearchConfig:
        """Test GithubComTencentWeKnoraInternalTypesWebSearchConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesWebSearchConfig`
        """
        model = GithubComTencentWeKnoraInternalTypesWebSearchConfig()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesWebSearchConfig(
                api_key = '',
                blacklist = [
                    ''
                    ],
                compression_method = '',
                document_fragments = 56,
                embedding_dimension = 56,
                embedding_model_id = '',
                include_date = True,
                max_results = 56,
                provider = '',
                rerank_model_id = ''
            )
        else:
            return GithubComTencentWeKnoraInternalTypesWebSearchConfig(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesWebSearchConfig(self):
        """Test GithubComTencentWeKnoraInternalTypesWebSearchConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
