# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_knowledge_base import GithubComTencentWeKnoraInternalTypesKnowledgeBase

class TestGithubComTencentWeKnoraInternalTypesKnowledgeBase(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesKnowledgeBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesKnowledgeBase:
        """Test GithubComTencentWeKnoraInternalTypesKnowledgeBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesKnowledgeBase`
        """
        model = GithubComTencentWeKnoraInternalTypesKnowledgeBase()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesKnowledgeBase(
                chunk_count = 56,
                chunking_config = weknora.models.github_com_tencent_we_knora_internal_types/chunking_config.github_com_Tencent_WeKnora_internal_types.ChunkingConfig(
                    chunk_overlap = 56, 
                    chunk_size = 56, 
                    enable_multimodal = True, 
                    separators = [
                        ''
                        ], ),
                cos_config = weknora.models.github_com_tencent_we_knora_internal_types/storage_config.github_com_Tencent_WeKnora_internal_types.StorageConfig(
                    app_id = '', 
                    bucket_name = '', 
                    path_prefix = '', 
                    provider = '', 
                    region = '', 
                    secret_id = '', 
                    secret_key = '', ),
                created_at = '',
                deleted_at = weknora.models.gorm/deleted_at.gorm.DeletedAt(
                    time = '', 
                    valid = True, ),
                description = '',
                embedding_model_id = '',
                extract_config = weknora.models.github_com_tencent_we_knora_internal_types/extract_config.github_com_Tencent_WeKnora_internal_types.ExtractConfig(
                    enabled = True, 
                    nodes = [
                        weknora.models.github_com_tencent_we_knora_internal_types/graph_node.github_com_Tencent_WeKnora_internal_types.GraphNode(
                            attributes = [
                                ''
                                ], 
                            chunks = [
                                ''
                                ], 
                            name = '', )
                        ], 
                    relations = [
                        weknora.models.github_com_tencent_we_knora_internal_types/graph_relation.github_com_Tencent_WeKnora_internal_types.GraphRelation(
                            node1 = '', 
                            node2 = '', 
                            type = '', )
                        ], 
                    tags = [
                        ''
                        ], 
                    text = '', ),
                faq_config = weknora.models.github_com_tencent_we_knora_internal_types/faq_config.github_com_Tencent_WeKnora_internal_types.FAQConfig(
                    index_mode = 'question_only', 
                    question_index_mode = 'combined', ),
                id = '',
                image_processing_config = weknora.models.github_com_tencent_we_knora_internal_types/image_processing_config.github_com_Tencent_WeKnora_internal_types.ImageProcessingConfig(
                    model_id = '', ),
                is_processing = True,
                is_temporary = True,
                knowledge_count = 56,
                name = '',
                processing_count = 56,
                question_generation_config = weknora.models.github_com_tencent_we_knora_internal_types/question_generation_config.github_com_Tencent_WeKnora_internal_types.QuestionGenerationConfig(
                    enabled = True, 
                    question_count = 56, ),
                summary_model_id = '',
                tenant_id = 56,
                type = '',
                updated_at = '',
                vlm_config = weknora.models.github_com_tencent_we_knora_internal_types/vlm_config.github_com_Tencent_WeKnora_internal_types.VLMConfig(
                    api_key = '', 
                    base_url = '', 
                    enabled = True, 
                    interface_type = '', 
                    model_id = '', 
                    model_name = '', )
            )
        else:
            return GithubComTencentWeKnoraInternalTypesKnowledgeBase(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesKnowledgeBase(self):
        """Test GithubComTencentWeKnoraInternalTypesKnowledgeBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
