# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.internal_handler_kb_model_config_request_multimodal_cos import InternalHandlerKBModelConfigRequestMultimodalCos

class TestInternalHandlerKBModelConfigRequestMultimodalCos(unittest.TestCase):
    """InternalHandlerKBModelConfigRequestMultimodalCos unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlerKBModelConfigRequestMultimodalCos:
        """Test InternalHandlerKBModelConfigRequestMultimodalCos
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlerKBModelConfigRequestMultimodalCos`
        """
        model = InternalHandlerKBModelConfigRequestMultimodalCos()
        if include_optional:
            return InternalHandlerKBModelConfigRequestMultimodalCos(
                app_id = '',
                bucket_name = '',
                path_prefix = '',
                region = '',
                secret_id = '',
                secret_key = ''
            )
        else:
            return InternalHandlerKBModelConfigRequestMultimodalCos(
        )
        """

    def testInternalHandlerKBModelConfigRequestMultimodalCos(self):
        """Test InternalHandlerKBModelConfigRequestMultimodalCos"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
