# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_faq_entry_fields_update import GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate

class TestGithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate:
        """Test GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate`
        """
        model = GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate(
                is_enabled = True,
                is_recommended = True,
                tag_id = ''
            )
        else:
            return GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate(self):
        """Test GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
