# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weknora.models.github_com_tencent_we_knora_internal_types_search_params import GithubComTencentWeKnoraInternalTypesSearchParams

class TestGithubComTencentWeKnoraInternalTypesSearchParams(unittest.TestCase):
    """GithubComTencentWeKnoraInternalTypesSearchParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComTencentWeKnoraInternalTypesSearchParams:
        """Test GithubComTencentWeKnoraInternalTypesSearchParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComTencentWeKnoraInternalTypesSearchParams`
        """
        model = GithubComTencentWeKnoraInternalTypesSearchParams()
        if include_optional:
            return GithubComTencentWeKnoraInternalTypesSearchParams(
                disable_keywords_match = True,
                disable_vector_match = True,
                keyword_threshold = 1.337,
                knowledge_ids = [
                    ''
                    ],
                match_count = 56,
                query_text = '',
                vector_threshold = 1.337
            )
        else:
            return GithubComTencentWeKnoraInternalTypesSearchParams(
        )
        """

    def testGithubComTencentWeKnoraInternalTypesSearchParams(self):
        """Test GithubComTencentWeKnoraInternalTypesSearchParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
