# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesSummaryConfig(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesSummaryConfig
    """ # noqa: E501
    context_template: Optional[StrictStr] = Field(default=None, description="Context template")
    frequency_penalty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Frequency penalty")
    max_completion_tokens: Optional[StrictInt] = Field(default=None, description="Max completion tokens")
    max_tokens: Optional[StrictInt] = Field(default=None, description="Max tokens")
    no_match_prefix: Optional[StrictStr] = Field(default=None, description="No match prefix")
    presence_penalty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Presence penalty")
    prompt: Optional[StrictStr] = Field(default=None, description="Prompt")
    repeat_penalty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Repeat penalty")
    seed: Optional[StrictInt] = Field(default=None, description="Seed")
    temperature: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Temperature")
    top_k: Optional[StrictInt] = Field(default=None, description="TopK")
    top_p: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="TopP")
    __properties: ClassVar[List[str]] = ["context_template", "frequency_penalty", "max_completion_tokens", "max_tokens", "no_match_prefix", "presence_penalty", "prompt", "repeat_penalty", "seed", "temperature", "top_k", "top_p"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesSummaryConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesSummaryConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "context_template": obj.get("context_template"),
            "frequency_penalty": obj.get("frequency_penalty"),
            "max_completion_tokens": obj.get("max_completion_tokens"),
            "max_tokens": obj.get("max_tokens"),
            "no_match_prefix": obj.get("no_match_prefix"),
            "presence_penalty": obj.get("presence_penalty"),
            "prompt": obj.get("prompt"),
            "repeat_penalty": obj.get("repeat_penalty"),
            "seed": obj.get("seed"),
            "temperature": obj.get("temperature"),
            "top_k": obj.get("top_k"),
            "top_p": obj.get("top_p")
        })
        return _obj


