# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesWebSearchConfig(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesWebSearchConfig
    """ # noqa: E501
    api_key: Optional[StrictStr] = Field(default=None, description="API密钥（如果需要）")
    blacklist: Optional[List[StrictStr]] = Field(default=None, description="黑名单规则列表")
    compression_method: Optional[StrictStr] = Field(default=None, description="压缩方法：none, summary, extract, rag")
    document_fragments: Optional[StrictInt] = Field(default=None, description="文档片段数量（用于RAG压缩）")
    embedding_dimension: Optional[StrictInt] = Field(default=None, description="嵌入维度（用于RAG压缩）")
    embedding_model_id: Optional[StrictStr] = Field(default=None, description="RAG压缩相关配置")
    include_date: Optional[StrictBool] = Field(default=None, description="是否包含日期")
    max_results: Optional[StrictInt] = Field(default=None, description="最大搜索结果数")
    provider: Optional[StrictStr] = Field(default=None, description="搜索引擎提供商ID")
    rerank_model_id: Optional[StrictStr] = Field(default=None, description="重排模型ID（用于RAG压缩）")
    __properties: ClassVar[List[str]] = ["api_key", "blacklist", "compression_method", "document_fragments", "embedding_dimension", "embedding_model_id", "include_date", "max_results", "provider", "rerank_model_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesWebSearchConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesWebSearchConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_key": obj.get("api_key"),
            "blacklist": obj.get("blacklist"),
            "compression_method": obj.get("compression_method"),
            "document_fragments": obj.get("document_fragments"),
            "embedding_dimension": obj.get("embedding_dimension"),
            "embedding_model_id": obj.get("embedding_model_id"),
            "include_date": obj.get("include_date"),
            "max_results": obj.get("max_results"),
            "provider": obj.get("provider"),
            "rerank_model_id": obj.get("rerank_model_id")
        })
        return _obj


