# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesStorageConfig(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesStorageConfig
    """ # noqa: E501
    app_id: Optional[StrictStr] = Field(default=None, description="App ID")
    bucket_name: Optional[StrictStr] = Field(default=None, description="Bucket Name")
    path_prefix: Optional[StrictStr] = Field(default=None, description="Path Prefix")
    provider: Optional[StrictStr] = Field(default=None, description="Provider")
    region: Optional[StrictStr] = Field(default=None, description="Region")
    secret_id: Optional[StrictStr] = Field(default=None, description="Secret ID")
    secret_key: Optional[StrictStr] = Field(default=None, description="Secret Key")
    __properties: ClassVar[List[str]] = ["app_id", "bucket_name", "path_prefix", "provider", "region", "secret_id", "secret_key"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesStorageConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesStorageConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "app_id": obj.get("app_id"),
            "bucket_name": obj.get("bucket_name"),
            "path_prefix": obj.get("path_prefix"),
            "provider": obj.get("provider"),
            "region": obj.get("region"),
            "secret_id": obj.get("secret_id"),
            "secret_key": obj.get("secret_key")
        })
        return _obj


