# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GithubComTencentWeKnoraInternalErrorsErrorCode(int, Enum):
    """
    GithubComTencentWeKnoraInternalErrorsErrorCode
    """

    """
    allowed enum values
    """
    ErrBadRequest = 1000
    ErrUnauthorized = 1001
    ErrForbidden = 1002
    ErrNotFound = 1003
    ErrMethodNotAllowed = 1004
    ErrConflict = 1005
    ErrTooManyRequests = 1006
    ErrInternalServer = 1007
    ErrServiceUnavailable = 1008
    ErrTimeout = 1009
    ErrValidation = 1010
    ErrTenantNotFound = 2000
    ErrTenantAlreadyExists = 2001
    ErrTenantInactive = 2002
    ErrTenantNameRequired = 2003
    ErrTenantInvalidStatus = 2004
    ErrAgentMissingThinkingModel = 2100
    ErrAgentMissingAllowedTools = 2101
    ErrAgentInvalidMaxIterations = 2102
    ErrAgentInvalidTemperature = 2103

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GithubComTencentWeKnoraInternalErrorsErrorCode from a JSON string"""
        return cls(json.loads(json_str))


