# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesAgentConfig(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesAgentConfig
    """ # noqa: E501
    allowed_tools: Optional[List[StrictStr]] = Field(default=None, description="List of allowed tool names")
    knowledge_bases: Optional[List[StrictStr]] = Field(default=None, description="Accessible knowledge base IDs")
    knowledge_ids: Optional[List[StrictStr]] = Field(default=None, description="Accessible knowledge IDs (individual documents)")
    max_iterations: Optional[StrictInt] = Field(default=None, description="Maximum number of ReAct iterations")
    reflection_enabled: Optional[StrictBool] = Field(default=None, description="Whether to enable reflection")
    system_prompt_web_disabled: Optional[StrictStr] = Field(default=None, description="Custom prompt when web search is disabled")
    system_prompt_web_enabled: Optional[StrictStr] = Field(default=None, description="Custom prompt when web search is enabled")
    temperature: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="LLM temperature for agent")
    use_custom_system_prompt: Optional[StrictBool] = Field(default=None, description="Whether to use custom system prompt instead of default")
    web_search_enabled: Optional[StrictBool] = Field(default=None, description="Whether web search tool is enabled")
    web_search_max_results: Optional[StrictInt] = Field(default=None, description="Maximum number of web search results (default: 5)")
    __properties: ClassVar[List[str]] = ["allowed_tools", "knowledge_bases", "knowledge_ids", "max_iterations", "reflection_enabled", "system_prompt_web_disabled", "system_prompt_web_enabled", "temperature", "use_custom_system_prompt", "web_search_enabled", "web_search_max_results"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesAgentConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesAgentConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed_tools": obj.get("allowed_tools"),
            "knowledge_bases": obj.get("knowledge_bases"),
            "knowledge_ids": obj.get("knowledge_ids"),
            "max_iterations": obj.get("max_iterations"),
            "reflection_enabled": obj.get("reflection_enabled"),
            "system_prompt_web_disabled": obj.get("system_prompt_web_disabled"),
            "system_prompt_web_enabled": obj.get("system_prompt_web_enabled"),
            "temperature": obj.get("temperature"),
            "use_custom_system_prompt": obj.get("use_custom_system_prompt"),
            "web_search_enabled": obj.get("web_search_enabled"),
            "web_search_max_results": obj.get("web_search_max_results")
        })
        return _obj


