# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from weknora.models.gorm_deleted_at import GormDeletedAt
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesKnowledge(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesKnowledge
    """ # noqa: E501
    created_at: Optional[StrictStr] = Field(default=None, description="Creation time of the knowledge")
    deleted_at: Optional[GormDeletedAt] = Field(default=None, description="Deletion time of the knowledge")
    description: Optional[StrictStr] = Field(default=None, description="Description of the knowledge")
    embedding_model_id: Optional[StrictStr] = Field(default=None, description="ID of the embedding model")
    enable_status: Optional[StrictStr] = Field(default=None, description="Enable status of the knowledge")
    error_message: Optional[StrictStr] = Field(default=None, description="Error message of the knowledge")
    file_hash: Optional[StrictStr] = Field(default=None, description="File hash of the knowledge")
    file_name: Optional[StrictStr] = Field(default=None, description="File name of the knowledge")
    file_path: Optional[StrictStr] = Field(default=None, description="File path of the knowledge")
    file_size: Optional[StrictInt] = Field(default=None, description="File size of the knowledge")
    file_type: Optional[StrictStr] = Field(default=None, description="File type of the knowledge")
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier of the knowledge")
    knowledge_base_id: Optional[StrictStr] = Field(default=None, description="ID of the knowledge base")
    knowledge_base_name: Optional[StrictStr] = Field(default=None, description="Knowledge base name (not stored in database, populated on query)")
    metadata: Optional[List[StrictInt]] = Field(default=None, description="Metadata of the knowledge")
    parse_status: Optional[StrictStr] = Field(default=None, description="Parse status of the knowledge")
    processed_at: Optional[StrictStr] = Field(default=None, description="Processed time of the knowledge")
    source: Optional[StrictStr] = Field(default=None, description="Source of the knowledge")
    storage_size: Optional[StrictInt] = Field(default=None, description="Storage size of the knowledge")
    summary_status: Optional[StrictStr] = Field(default=None, description="Summary status for async summary generation")
    tag_id: Optional[StrictStr] = Field(default=None, description="Optional tag ID for categorization within a knowledge base")
    tenant_id: Optional[StrictInt] = Field(default=None, description="Tenant ID")
    title: Optional[StrictStr] = Field(default=None, description="Title of the knowledge")
    type: Optional[StrictStr] = Field(default=None, description="Type of the knowledge")
    updated_at: Optional[StrictStr] = Field(default=None, description="Last updated time of the knowledge")
    __properties: ClassVar[List[str]] = ["created_at", "deleted_at", "description", "embedding_model_id", "enable_status", "error_message", "file_hash", "file_name", "file_path", "file_size", "file_type", "id", "knowledge_base_id", "knowledge_base_name", "metadata", "parse_status", "processed_at", "source", "storage_size", "summary_status", "tag_id", "tenant_id", "title", "type", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesKnowledge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of deleted_at
        if self.deleted_at:
            _dict['deleted_at'] = self.deleted_at.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesKnowledge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "deleted_at": GormDeletedAt.from_dict(obj["deleted_at"]) if obj.get("deleted_at") is not None else None,
            "description": obj.get("description"),
            "embedding_model_id": obj.get("embedding_model_id"),
            "enable_status": obj.get("enable_status"),
            "error_message": obj.get("error_message"),
            "file_hash": obj.get("file_hash"),
            "file_name": obj.get("file_name"),
            "file_path": obj.get("file_path"),
            "file_size": obj.get("file_size"),
            "file_type": obj.get("file_type"),
            "id": obj.get("id"),
            "knowledge_base_id": obj.get("knowledge_base_id"),
            "knowledge_base_name": obj.get("knowledge_base_name"),
            "metadata": obj.get("metadata"),
            "parse_status": obj.get("parse_status"),
            "processed_at": obj.get("processed_at"),
            "source": obj.get("source"),
            "storage_size": obj.get("storage_size"),
            "summary_status": obj.get("summary_status"),
            "tag_id": obj.get("tag_id"),
            "tenant_id": obj.get("tenant_id"),
            "title": obj.get("title"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


