# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesConversationConfig(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesConversationConfig
    """ # noqa: E501
    context_template: Optional[StrictStr] = Field(default=None, description="ContextTemplate is the prompt template for summarizing retrieval results")
    embedding_top_k: Optional[StrictInt] = None
    enable_query_expansion: Optional[StrictBool] = None
    enable_rewrite: Optional[StrictBool] = None
    fallback_prompt: Optional[StrictStr] = None
    fallback_response: Optional[StrictStr] = None
    fallback_strategy: Optional[StrictStr] = Field(default=None, description="Fallback strategy")
    keyword_threshold: Optional[Union[StrictFloat, StrictInt]] = None
    max_completion_tokens: Optional[StrictInt] = Field(default=None, description="MaxTokens is the maximum number of tokens to generate")
    max_rounds: Optional[StrictInt] = Field(default=None, description="Retrieval & strategy parameters")
    prompt: Optional[StrictStr] = None
    rerank_model_id: Optional[StrictStr] = None
    rerank_threshold: Optional[Union[StrictFloat, StrictInt]] = None
    rerank_top_k: Optional[StrictInt] = None
    rewrite_prompt_system: Optional[StrictStr] = Field(default=None, description="Rewrite prompts")
    rewrite_prompt_user: Optional[StrictStr] = None
    summary_model_id: Optional[StrictStr] = Field(default=None, description="Model configuration")
    temperature: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Temperature controls the randomness of the model output")
    use_custom_context_template: Optional[StrictBool] = None
    use_custom_system_prompt: Optional[StrictBool] = Field(default=None, description="Prompt is the system prompt for normal mode")
    vector_threshold: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["context_template", "embedding_top_k", "enable_query_expansion", "enable_rewrite", "fallback_prompt", "fallback_response", "fallback_strategy", "keyword_threshold", "max_completion_tokens", "max_rounds", "prompt", "rerank_model_id", "rerank_threshold", "rerank_top_k", "rewrite_prompt_system", "rewrite_prompt_user", "summary_model_id", "temperature", "use_custom_context_template", "use_custom_system_prompt", "vector_threshold"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesConversationConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesConversationConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "context_template": obj.get("context_template"),
            "embedding_top_k": obj.get("embedding_top_k"),
            "enable_query_expansion": obj.get("enable_query_expansion"),
            "enable_rewrite": obj.get("enable_rewrite"),
            "fallback_prompt": obj.get("fallback_prompt"),
            "fallback_response": obj.get("fallback_response"),
            "fallback_strategy": obj.get("fallback_strategy"),
            "keyword_threshold": obj.get("keyword_threshold"),
            "max_completion_tokens": obj.get("max_completion_tokens"),
            "max_rounds": obj.get("max_rounds"),
            "prompt": obj.get("prompt"),
            "rerank_model_id": obj.get("rerank_model_id"),
            "rerank_threshold": obj.get("rerank_threshold"),
            "rerank_top_k": obj.get("rerank_top_k"),
            "rewrite_prompt_system": obj.get("rewrite_prompt_system"),
            "rewrite_prompt_user": obj.get("rewrite_prompt_user"),
            "summary_model_id": obj.get("summary_model_id"),
            "temperature": obj.get("temperature"),
            "use_custom_context_template": obj.get("use_custom_context_template"),
            "use_custom_system_prompt": obj.get("use_custom_system_prompt"),
            "vector_threshold": obj.get("vector_threshold")
        })
        return _obj


