# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from weknora.models.github_com_tencent_we_knora_internal_types_tenant import GithubComTencentWeKnoraInternalTypesTenant
from weknora.models.gorm_deleted_at import GormDeletedAt
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesUser(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesUser
    """ # noqa: E501
    avatar: Optional[StrictStr] = Field(default=None, description="Avatar URL of the user")
    can_access_all_tenants: Optional[StrictBool] = Field(default=None, description="Whether the user can access all tenants (cross-tenant access)")
    created_at: Optional[StrictStr] = Field(default=None, description="Creation time of the user")
    deleted_at: Optional[GormDeletedAt] = Field(default=None, description="Deletion time of the user")
    email: Optional[StrictStr] = Field(default=None, description="Email address of the user")
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier of the user")
    is_active: Optional[StrictBool] = Field(default=None, description="Whether the user is active")
    tenant: Optional[GithubComTencentWeKnoraInternalTypesTenant] = Field(default=None, description="Association relationship, not stored in the database")
    tenant_id: Optional[StrictInt] = Field(default=None, description="Tenant ID that the user belongs to")
    updated_at: Optional[StrictStr] = Field(default=None, description="Last updated time of the user")
    username: Optional[StrictStr] = Field(default=None, description="Username of the user")
    __properties: ClassVar[List[str]] = ["avatar", "can_access_all_tenants", "created_at", "deleted_at", "email", "id", "is_active", "tenant", "tenant_id", "updated_at", "username"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesUser from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of deleted_at
        if self.deleted_at:
            _dict['deleted_at'] = self.deleted_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tenant
        if self.tenant:
            _dict['tenant'] = self.tenant.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesUser from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "avatar": obj.get("avatar"),
            "can_access_all_tenants": obj.get("can_access_all_tenants"),
            "created_at": obj.get("created_at"),
            "deleted_at": GormDeletedAt.from_dict(obj["deleted_at"]) if obj.get("deleted_at") is not None else None,
            "email": obj.get("email"),
            "id": obj.get("id"),
            "is_active": obj.get("is_active"),
            "tenant": GithubComTencentWeKnoraInternalTypesTenant.from_dict(obj["tenant"]) if obj.get("tenant") is not None else None,
            "tenant_id": obj.get("tenant_id"),
            "updated_at": obj.get("updated_at"),
            "username": obj.get("username")
        })
        return _obj


