# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from weknora.models.github_com_tencent_we_knora_internal_types_agent_step import GithubComTencentWeKnoraInternalTypesAgentStep
from weknora.models.github_com_tencent_we_knora_internal_types_mentioned_item import GithubComTencentWeKnoraInternalTypesMentionedItem
from weknora.models.github_com_tencent_we_knora_internal_types_search_result import GithubComTencentWeKnoraInternalTypesSearchResult
from weknora.models.gorm_deleted_at import GormDeletedAt
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesMessage(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesMessage
    """ # noqa: E501
    agent_steps: Optional[List[GithubComTencentWeKnoraInternalTypesAgentStep]] = Field(default=None, description="Agent execution steps (only for assistant messages generated by agent) This contains the detailed reasoning process and tool calls made by the agent Stored for user history display, but NOT included in LLM context to avoid redundancy")
    content: Optional[StrictStr] = Field(default=None, description="Message text content")
    created_at: Optional[StrictStr] = Field(default=None, description="Message creation timestamp")
    deleted_at: Optional[GormDeletedAt] = Field(default=None, description="Soft delete timestamp")
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier for the message")
    is_completed: Optional[StrictBool] = Field(default=None, description="Whether message generation is complete")
    knowledge_references: Optional[List[GithubComTencentWeKnoraInternalTypesSearchResult]] = Field(default=None, description="References to knowledge chunks used in the response")
    mentioned_items: Optional[List[GithubComTencentWeKnoraInternalTypesMentionedItem]] = Field(default=None, description="Mentioned knowledge bases and files (for user messages) Stores the @mentioned items when user sends a message")
    request_id: Optional[StrictStr] = Field(default=None, description="Request identifier for tracking API requests")
    role: Optional[StrictStr] = Field(default=None, description="Message role: \"user\", \"assistant\", \"system\"")
    session_id: Optional[StrictStr] = Field(default=None, description="ID of the session this message belongs to")
    updated_at: Optional[StrictStr] = Field(default=None, description="Last update timestamp")
    __properties: ClassVar[List[str]] = ["agent_steps", "content", "created_at", "deleted_at", "id", "is_completed", "knowledge_references", "mentioned_items", "request_id", "role", "session_id", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in agent_steps (list)
        _items = []
        if self.agent_steps:
            for _item_agent_steps in self.agent_steps:
                if _item_agent_steps:
                    _items.append(_item_agent_steps.to_dict())
            _dict['agent_steps'] = _items
        # override the default output from pydantic by calling `to_dict()` of deleted_at
        if self.deleted_at:
            _dict['deleted_at'] = self.deleted_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in knowledge_references (list)
        _items = []
        if self.knowledge_references:
            for _item_knowledge_references in self.knowledge_references:
                if _item_knowledge_references:
                    _items.append(_item_knowledge_references.to_dict())
            _dict['knowledge_references'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in mentioned_items (list)
        _items = []
        if self.mentioned_items:
            for _item_mentioned_items in self.mentioned_items:
                if _item_mentioned_items:
                    _items.append(_item_mentioned_items.to_dict())
            _dict['mentioned_items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_steps": [GithubComTencentWeKnoraInternalTypesAgentStep.from_dict(_item) for _item in obj["agent_steps"]] if obj.get("agent_steps") is not None else None,
            "content": obj.get("content"),
            "created_at": obj.get("created_at"),
            "deleted_at": GormDeletedAt.from_dict(obj["deleted_at"]) if obj.get("deleted_at") is not None else None,
            "id": obj.get("id"),
            "is_completed": obj.get("is_completed"),
            "knowledge_references": [GithubComTencentWeKnoraInternalTypesSearchResult.from_dict(_item) for _item in obj["knowledge_references"]] if obj.get("knowledge_references") is not None else None,
            "mentioned_items": [GithubComTencentWeKnoraInternalTypesMentionedItem.from_dict(_item) for _item in obj["mentioned_items"]] if obj.get("mentioned_items") is not None else None,
            "request_id": obj.get("request_id"),
            "role": obj.get("role"),
            "session_id": obj.get("session_id"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


