# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GithubComTencentWeKnoraInternalTypesMatchType(int, Enum):
    """
    GithubComTencentWeKnoraInternalTypesMatchType
    """

    """
    allowed enum values
    """
    MatchTypeEmbedding = 0
    MatchTypeKeywords = 1
    MatchTypeNearByChunk = 2
    MatchTypeHistory = 3
    MatchTypeParentChunk = 4
    MatchTypeRelationChunk = 5
    MatchTypeGraph = 6
    MatchTypeWebSearch = 7
    MatchTypeDirectLoad = 8

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GithubComTencentWeKnoraInternalTypesMatchType from a JSON string"""
        return cls(json.loads(json_str))


