# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GithubComTencentWeKnoraInternalTypesFAQIndexMode(str, Enum):
    """
    GithubComTencentWeKnoraInternalTypesFAQIndexMode
    """

    """
    allowed enum values
    """
    FAQIndexModeQuestionOnly = 'question_only'
    FAQIndexModeQuestionAnswer = 'question_answer'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GithubComTencentWeKnoraInternalTypesFAQIndexMode from a JSON string"""
        return cls(json.loads(json_str))


