# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from weknora.models.github_com_tencent_we_knora_internal_types_retriever_engine_params import GithubComTencentWeKnoraInternalTypesRetrieverEngineParams
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesRetrieverEngines(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesRetrieverEngines
    """ # noqa: E501
    engines: Optional[List[GithubComTencentWeKnoraInternalTypesRetrieverEngineParams]] = None
    __properties: ClassVar[List[str]] = ["engines"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesRetrieverEngines from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in engines (list)
        _items = []
        if self.engines:
            for _item_engines in self.engines:
                if _item_engines:
                    _items.append(_item_engines.to_dict())
            _dict['engines'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesRetrieverEngines from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "engines": [GithubComTencentWeKnoraInternalTypesRetrieverEngineParams.from_dict(_item) for _item in obj["engines"]] if obj.get("engines") is not None else None
        })
        return _obj


