# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from weknora.models.github_com_tencent_we_knora_internal_types_agent_config import GithubComTencentWeKnoraInternalTypesAgentConfig
from weknora.models.github_com_tencent_we_knora_internal_types_context_config import GithubComTencentWeKnoraInternalTypesContextConfig
from weknora.models.github_com_tencent_we_knora_internal_types_conversation_config import GithubComTencentWeKnoraInternalTypesConversationConfig
from weknora.models.github_com_tencent_we_knora_internal_types_retriever_engines import GithubComTencentWeKnoraInternalTypesRetrieverEngines
from weknora.models.github_com_tencent_we_knora_internal_types_web_search_config import GithubComTencentWeKnoraInternalTypesWebSearchConfig
from weknora.models.gorm_deleted_at import GormDeletedAt
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesTenant(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesTenant
    """ # noqa: E501
    agent_config: Optional[GithubComTencentWeKnoraInternalTypesAgentConfig] = Field(default=None, description="Global Agent configuration for this tenant (default for all sessions)")
    api_key: Optional[StrictStr] = Field(default=None, description="API key")
    business: Optional[StrictStr] = Field(default=None, description="Business")
    context_config: Optional[GithubComTencentWeKnoraInternalTypesContextConfig] = Field(default=None, description="Global Context configuration for this tenant (default for all sessions)")
    conversation_config: Optional[GithubComTencentWeKnoraInternalTypesConversationConfig] = Field(default=None, description="Global Conversation configuration for this tenant (default for normal mode sessions)")
    created_at: Optional[StrictStr] = Field(default=None, description="Creation time")
    deleted_at: Optional[GormDeletedAt] = Field(default=None, description="Deletion time")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    id: Optional[StrictInt] = Field(default=None, description="ID")
    name: Optional[StrictStr] = Field(default=None, description="Name")
    retriever_engines: Optional[GithubComTencentWeKnoraInternalTypesRetrieverEngines] = Field(default=None, description="Retriever engines")
    status: Optional[StrictStr] = Field(default=None, description="Status")
    storage_quota: Optional[StrictInt] = Field(default=None, description="Storage quota (Bytes), default is 10GB, including vector, original file, text, index, etc.")
    storage_used: Optional[StrictInt] = Field(default=None, description="Storage used (Bytes)")
    updated_at: Optional[StrictStr] = Field(default=None, description="Last updated time")
    web_search_config: Optional[GithubComTencentWeKnoraInternalTypesWebSearchConfig] = Field(default=None, description="Global WebSearch configuration for this tenant")
    __properties: ClassVar[List[str]] = ["agent_config", "api_key", "business", "context_config", "conversation_config", "created_at", "deleted_at", "description", "id", "name", "retriever_engines", "status", "storage_quota", "storage_used", "updated_at", "web_search_config"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesTenant from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of agent_config
        if self.agent_config:
            _dict['agent_config'] = self.agent_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of context_config
        if self.context_config:
            _dict['context_config'] = self.context_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of conversation_config
        if self.conversation_config:
            _dict['conversation_config'] = self.conversation_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deleted_at
        if self.deleted_at:
            _dict['deleted_at'] = self.deleted_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of retriever_engines
        if self.retriever_engines:
            _dict['retriever_engines'] = self.retriever_engines.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_search_config
        if self.web_search_config:
            _dict['web_search_config'] = self.web_search_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesTenant from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_config": GithubComTencentWeKnoraInternalTypesAgentConfig.from_dict(obj["agent_config"]) if obj.get("agent_config") is not None else None,
            "api_key": obj.get("api_key"),
            "business": obj.get("business"),
            "context_config": GithubComTencentWeKnoraInternalTypesContextConfig.from_dict(obj["context_config"]) if obj.get("context_config") is not None else None,
            "conversation_config": GithubComTencentWeKnoraInternalTypesConversationConfig.from_dict(obj["conversation_config"]) if obj.get("conversation_config") is not None else None,
            "created_at": obj.get("created_at"),
            "deleted_at": GormDeletedAt.from_dict(obj["deleted_at"]) if obj.get("deleted_at") is not None else None,
            "description": obj.get("description"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "retriever_engines": GithubComTencentWeKnoraInternalTypesRetrieverEngines.from_dict(obj["retriever_engines"]) if obj.get("retriever_engines") is not None else None,
            "status": obj.get("status"),
            "storage_quota": obj.get("storage_quota"),
            "storage_used": obj.get("storage_used"),
            "updated_at": obj.get("updated_at"),
            "web_search_config": GithubComTencentWeKnoraInternalTypesWebSearchConfig.from_dict(obj["web_search_config"]) if obj.get("web_search_config") is not None else None
        })
        return _obj


