# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from weknora.models.github_com_tencent_we_knora_internal_types_faq_entry_fields_update import GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate
    """ # noqa: E501
    by_id: Optional[Dict[str, GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate]] = Field(default=None, description="ByID 按条目ID更新，key为条目ID")
    by_tag: Optional[Dict[str, GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate]] = Field(default=None, description="ByTag 按Tag批量更新，key为TagID（空字符串表示未分类）")
    __properties: ClassVar[List[str]] = ["by_id", "by_tag"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in by_id (dict)
        _field_dict = {}
        if self.by_id:
            for _key_by_id in self.by_id:
                if self.by_id[_key_by_id]:
                    _field_dict[_key_by_id] = self.by_id[_key_by_id].to_dict()
            _dict['by_id'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in by_tag (dict)
        _field_dict = {}
        if self.by_tag:
            for _key_by_tag in self.by_tag:
                if self.by_tag[_key_by_tag]:
                    _field_dict[_key_by_tag] = self.by_tag[_key_by_tag].to_dict()
            _dict['by_tag'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesFAQEntryFieldsBatchUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "by_id": dict(
                (_k, GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate.from_dict(_v))
                for _k, _v in obj["by_id"].items()
            )
            if obj.get("by_id") is not None
            else None,
            "by_tag": dict(
                (_k, GithubComTencentWeKnoraInternalTypesFAQEntryFieldsUpdate.from_dict(_v))
                for _k, _v in obj["by_tag"].items()
            )
            if obj.get("by_tag") is not None
            else None
        })
        return _obj


