# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from weknora.models.github_com_tencent_we_knora_internal_types_context_config import GithubComTencentWeKnoraInternalTypesContextConfig
from weknora.models.github_com_tencent_we_knora_internal_types_fallback_strategy import GithubComTencentWeKnoraInternalTypesFallbackStrategy
from weknora.models.github_com_tencent_we_knora_internal_types_session_agent_config import GithubComTencentWeKnoraInternalTypesSessionAgentConfig
from weknora.models.github_com_tencent_we_knora_internal_types_summary_config import GithubComTencentWeKnoraInternalTypesSummaryConfig
from weknora.models.gorm_deleted_at import GormDeletedAt
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesSession(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesSession
    """ # noqa: E501
    agent_config: Optional[GithubComTencentWeKnoraInternalTypesSessionAgentConfig] = Field(default=None, description="Agent 配置（会话级别，仅存储enabled和knowledge_bases）")
    context_config: Optional[GithubComTencentWeKnoraInternalTypesContextConfig] = Field(default=None, description="上下文管理配置（可选）")
    created_at: Optional[StrictStr] = None
    deleted_at: Optional[GormDeletedAt] = None
    description: Optional[StrictStr] = Field(default=None, description="Description")
    embedding_top_k: Optional[StrictInt] = Field(default=None, description="向量召回TopK")
    enable_rewrite: Optional[StrictBool] = Field(default=None, description="多轮改写开关")
    fallback_response: Optional[StrictStr] = Field(default=None, description="固定回复内容")
    fallback_strategy: Optional[GithubComTencentWeKnoraInternalTypesFallbackStrategy] = Field(default=None, description="兜底策略")
    id: Optional[StrictStr] = Field(default=None, description="ID")
    keyword_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="关键词召回阈值")
    knowledge_base_id: Optional[StrictStr] = Field(default=None, description="Strategy configuration")
    max_rounds: Optional[StrictInt] = Field(default=None, description="多轮保持轮数")
    rerank_model_id: Optional[StrictStr] = Field(default=None, description="排序模型ID")
    rerank_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="排序阈值")
    rerank_top_k: Optional[StrictInt] = Field(default=None, description="排序TopK")
    summary_model_id: Optional[StrictStr] = Field(default=None, description="总结模型ID")
    summary_parameters: Optional[GithubComTencentWeKnoraInternalTypesSummaryConfig] = Field(default=None, description="总结模型参数")
    tenant_id: Optional[StrictInt] = Field(default=None, description="Tenant ID")
    title: Optional[StrictStr] = Field(default=None, description="Title")
    updated_at: Optional[StrictStr] = None
    vector_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="向量召回阈值")
    __properties: ClassVar[List[str]] = ["agent_config", "context_config", "created_at", "deleted_at", "description", "embedding_top_k", "enable_rewrite", "fallback_response", "fallback_strategy", "id", "keyword_threshold", "knowledge_base_id", "max_rounds", "rerank_model_id", "rerank_threshold", "rerank_top_k", "summary_model_id", "summary_parameters", "tenant_id", "title", "updated_at", "vector_threshold"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesSession from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of agent_config
        if self.agent_config:
            _dict['agent_config'] = self.agent_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of context_config
        if self.context_config:
            _dict['context_config'] = self.context_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deleted_at
        if self.deleted_at:
            _dict['deleted_at'] = self.deleted_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of summary_parameters
        if self.summary_parameters:
            _dict['summary_parameters'] = self.summary_parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesSession from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_config": GithubComTencentWeKnoraInternalTypesSessionAgentConfig.from_dict(obj["agent_config"]) if obj.get("agent_config") is not None else None,
            "context_config": GithubComTencentWeKnoraInternalTypesContextConfig.from_dict(obj["context_config"]) if obj.get("context_config") is not None else None,
            "created_at": obj.get("created_at"),
            "deleted_at": GormDeletedAt.from_dict(obj["deleted_at"]) if obj.get("deleted_at") is not None else None,
            "description": obj.get("description"),
            "embedding_top_k": obj.get("embedding_top_k"),
            "enable_rewrite": obj.get("enable_rewrite"),
            "fallback_response": obj.get("fallback_response"),
            "fallback_strategy": obj.get("fallback_strategy"),
            "id": obj.get("id"),
            "keyword_threshold": obj.get("keyword_threshold"),
            "knowledge_base_id": obj.get("knowledge_base_id"),
            "max_rounds": obj.get("max_rounds"),
            "rerank_model_id": obj.get("rerank_model_id"),
            "rerank_threshold": obj.get("rerank_threshold"),
            "rerank_top_k": obj.get("rerank_top_k"),
            "summary_model_id": obj.get("summary_model_id"),
            "summary_parameters": GithubComTencentWeKnoraInternalTypesSummaryConfig.from_dict(obj["summary_parameters"]) if obj.get("summary_parameters") is not None else None,
            "tenant_id": obj.get("tenant_id"),
            "title": obj.get("title"),
            "updated_at": obj.get("updated_at"),
            "vector_threshold": obj.get("vector_threshold")
        })
        return _obj


