# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesSearchParams(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesSearchParams
    """ # noqa: E501
    disable_keywords_match: Optional[StrictBool] = None
    disable_vector_match: Optional[StrictBool] = None
    keyword_threshold: Optional[Union[StrictFloat, StrictInt]] = None
    knowledge_ids: Optional[List[StrictStr]] = None
    match_count: Optional[StrictInt] = None
    query_text: Optional[StrictStr] = None
    vector_threshold: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["disable_keywords_match", "disable_vector_match", "keyword_threshold", "knowledge_ids", "match_count", "query_text", "vector_threshold"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesSearchParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesSearchParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "disable_keywords_match": obj.get("disable_keywords_match"),
            "disable_vector_match": obj.get("disable_vector_match"),
            "keyword_threshold": obj.get("keyword_threshold"),
            "knowledge_ids": obj.get("knowledge_ids"),
            "match_count": obj.get("match_count"),
            "query_text": obj.get("query_text"),
            "vector_threshold": obj.get("vector_threshold")
        })
        return _obj


