# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from weknora.models.github_com_tencent_we_knora_internal_types_chunking_config import GithubComTencentWeKnoraInternalTypesChunkingConfig
from weknora.models.github_com_tencent_we_knora_internal_types_extract_config import GithubComTencentWeKnoraInternalTypesExtractConfig
from weknora.models.github_com_tencent_we_knora_internal_types_faq_config import GithubComTencentWeKnoraInternalTypesFAQConfig
from weknora.models.github_com_tencent_we_knora_internal_types_image_processing_config import GithubComTencentWeKnoraInternalTypesImageProcessingConfig
from weknora.models.github_com_tencent_we_knora_internal_types_question_generation_config import GithubComTencentWeKnoraInternalTypesQuestionGenerationConfig
from weknora.models.github_com_tencent_we_knora_internal_types_storage_config import GithubComTencentWeKnoraInternalTypesStorageConfig
from weknora.models.github_com_tencent_we_knora_internal_types_vlm_config import GithubComTencentWeKnoraInternalTypesVLMConfig
from weknora.models.gorm_deleted_at import GormDeletedAt
from typing import Optional, Set
from typing_extensions import Self

class GithubComTencentWeKnoraInternalTypesKnowledgeBase(BaseModel):
    """
    GithubComTencentWeKnoraInternalTypesKnowledgeBase
    """ # noqa: E501
    chunk_count: Optional[StrictInt] = Field(default=None, description="Chunk count (not stored in database, calculated on query)")
    chunking_config: Optional[GithubComTencentWeKnoraInternalTypesChunkingConfig] = Field(default=None, description="Chunking configuration")
    cos_config: Optional[GithubComTencentWeKnoraInternalTypesStorageConfig] = Field(default=None, description="Storage config")
    created_at: Optional[StrictStr] = Field(default=None, description="Creation time of the knowledge base")
    deleted_at: Optional[GormDeletedAt] = Field(default=None, description="Deletion time of the knowledge base")
    description: Optional[StrictStr] = Field(default=None, description="Description of the knowledge base")
    embedding_model_id: Optional[StrictStr] = Field(default=None, description="ID of the embedding model")
    extract_config: Optional[GithubComTencentWeKnoraInternalTypesExtractConfig] = Field(default=None, description="Extract config")
    faq_config: Optional[GithubComTencentWeKnoraInternalTypesFAQConfig] = Field(default=None, description="FAQConfig stores FAQ specific configuration such as indexing strategy")
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier of the knowledge base")
    image_processing_config: Optional[GithubComTencentWeKnoraInternalTypesImageProcessingConfig] = Field(default=None, description="Image processing configuration")
    is_processing: Optional[StrictBool] = Field(default=None, description="IsProcessing indicates if there is a processing import task (for FAQ type knowledge bases)")
    is_temporary: Optional[StrictBool] = Field(default=None, description="Whether this knowledge base is temporary (ephemeral) and should be hidden from UI")
    knowledge_count: Optional[StrictInt] = Field(default=None, description="Knowledge count (not stored in database, calculated on query)")
    name: Optional[StrictStr] = Field(default=None, description="Name of the knowledge base")
    processing_count: Optional[StrictInt] = Field(default=None, description="ProcessingCount indicates the number of knowledge items being processed (for document type knowledge bases)")
    question_generation_config: Optional[GithubComTencentWeKnoraInternalTypesQuestionGenerationConfig] = Field(default=None, description="QuestionGenerationConfig stores question generation configuration for document knowledge bases")
    summary_model_id: Optional[StrictStr] = Field(default=None, description="Summary model ID")
    tenant_id: Optional[StrictInt] = Field(default=None, description="Tenant ID")
    type: Optional[StrictStr] = Field(default=None, description="Type of the knowledge base (document, faq, etc.)")
    updated_at: Optional[StrictStr] = Field(default=None, description="Last updated time of the knowledge base")
    vlm_config: Optional[GithubComTencentWeKnoraInternalTypesVLMConfig] = Field(default=None, description="VLM config")
    __properties: ClassVar[List[str]] = ["chunk_count", "chunking_config", "cos_config", "created_at", "deleted_at", "description", "embedding_model_id", "extract_config", "faq_config", "id", "image_processing_config", "is_processing", "is_temporary", "knowledge_count", "name", "processing_count", "question_generation_config", "summary_model_id", "tenant_id", "type", "updated_at", "vlm_config"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesKnowledgeBase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of chunking_config
        if self.chunking_config:
            _dict['chunking_config'] = self.chunking_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cos_config
        if self.cos_config:
            _dict['cos_config'] = self.cos_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deleted_at
        if self.deleted_at:
            _dict['deleted_at'] = self.deleted_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of extract_config
        if self.extract_config:
            _dict['extract_config'] = self.extract_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of faq_config
        if self.faq_config:
            _dict['faq_config'] = self.faq_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of image_processing_config
        if self.image_processing_config:
            _dict['image_processing_config'] = self.image_processing_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of question_generation_config
        if self.question_generation_config:
            _dict['question_generation_config'] = self.question_generation_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vlm_config
        if self.vlm_config:
            _dict['vlm_config'] = self.vlm_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComTencentWeKnoraInternalTypesKnowledgeBase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chunk_count": obj.get("chunk_count"),
            "chunking_config": GithubComTencentWeKnoraInternalTypesChunkingConfig.from_dict(obj["chunking_config"]) if obj.get("chunking_config") is not None else None,
            "cos_config": GithubComTencentWeKnoraInternalTypesStorageConfig.from_dict(obj["cos_config"]) if obj.get("cos_config") is not None else None,
            "created_at": obj.get("created_at"),
            "deleted_at": GormDeletedAt.from_dict(obj["deleted_at"]) if obj.get("deleted_at") is not None else None,
            "description": obj.get("description"),
            "embedding_model_id": obj.get("embedding_model_id"),
            "extract_config": GithubComTencentWeKnoraInternalTypesExtractConfig.from_dict(obj["extract_config"]) if obj.get("extract_config") is not None else None,
            "faq_config": GithubComTencentWeKnoraInternalTypesFAQConfig.from_dict(obj["faq_config"]) if obj.get("faq_config") is not None else None,
            "id": obj.get("id"),
            "image_processing_config": GithubComTencentWeKnoraInternalTypesImageProcessingConfig.from_dict(obj["image_processing_config"]) if obj.get("image_processing_config") is not None else None,
            "is_processing": obj.get("is_processing"),
            "is_temporary": obj.get("is_temporary"),
            "knowledge_count": obj.get("knowledge_count"),
            "name": obj.get("name"),
            "processing_count": obj.get("processing_count"),
            "question_generation_config": GithubComTencentWeKnoraInternalTypesQuestionGenerationConfig.from_dict(obj["question_generation_config"]) if obj.get("question_generation_config") is not None else None,
            "summary_model_id": obj.get("summary_model_id"),
            "tenant_id": obj.get("tenant_id"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at"),
            "vlm_config": GithubComTencentWeKnoraInternalTypesVLMConfig.from_dict(obj["vlm_config"]) if obj.get("vlm_config") is not None else None
        })
        return _obj


