# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from weknora.models.github_com_tencent_we_knora_internal_types_session_agent_config import GithubComTencentWeKnoraInternalTypesSessionAgentConfig
from weknora.models.internal_handler_session_session_strategy import InternalHandlerSessionSessionStrategy
from typing import Optional, Set
from typing_extensions import Self

class InternalHandlerSessionCreateSessionRequest(BaseModel):
    """
    InternalHandlerSessionCreateSessionRequest
    """ # noqa: E501
    agent_config: Optional[GithubComTencentWeKnoraInternalTypesSessionAgentConfig] = Field(default=None, description="Agent configuration (optional, session-level config only: enabled and knowledge_bases)")
    knowledge_base_id: Optional[StrictStr] = Field(default=None, description="ID of the associated knowledge base (optional, can be set/changed during queries)")
    session_strategy: Optional[InternalHandlerSessionSessionStrategy] = Field(default=None, description="Session strategy configuration")
    __properties: ClassVar[List[str]] = ["agent_config", "knowledge_base_id", "session_strategy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalHandlerSessionCreateSessionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of agent_config
        if self.agent_config:
            _dict['agent_config'] = self.agent_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of session_strategy
        if self.session_strategy:
            _dict['session_strategy'] = self.session_strategy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalHandlerSessionCreateSessionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_config": GithubComTencentWeKnoraInternalTypesSessionAgentConfig.from_dict(obj["agent_config"]) if obj.get("agent_config") is not None else None,
            "knowledge_base_id": obj.get("knowledge_base_id"),
            "session_strategy": InternalHandlerSessionSessionStrategy.from_dict(obj["session_strategy"]) if obj.get("session_strategy") is not None else None
        })
        return _obj


