# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InternalHandlerSessionSearchKnowledgeRequest(BaseModel):
    """
    InternalHandlerSessionSearchKnowledgeRequest
    """ # noqa: E501
    knowledge_base_id: Optional[StrictStr] = Field(default=None, description="Single knowledge base ID (for backward compatibility)")
    knowledge_base_ids: Optional[List[StrictStr]] = Field(default=None, description="IDs of knowledge bases to search (multi-KB support)")
    knowledge_ids: Optional[List[StrictStr]] = Field(default=None, description="IDs of specific knowledge (files) to search")
    query: StrictStr = Field(description="Query text to search for")
    __properties: ClassVar[List[str]] = ["knowledge_base_id", "knowledge_base_ids", "knowledge_ids", "query"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalHandlerSessionSearchKnowledgeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalHandlerSessionSearchKnowledgeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "knowledge_base_id": obj.get("knowledge_base_id"),
            "knowledge_base_ids": obj.get("knowledge_base_ids"),
            "knowledge_ids": obj.get("knowledge_ids"),
            "query": obj.get("query")
        })
        return _obj


