# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from weknora.models.internal_handler_session_mentioned_item_request import InternalHandlerSessionMentionedItemRequest
from typing import Optional, Set
from typing_extensions import Self

class InternalHandlerSessionCreateKnowledgeQARequest(BaseModel):
    """
    InternalHandlerSessionCreateKnowledgeQARequest
    """ # noqa: E501
    agent_enabled: Optional[StrictBool] = Field(default=None, description="Whether agent mode is enabled for this request")
    knowledge_base_ids: Optional[List[StrictStr]] = Field(default=None, description="Selected knowledge base ID for this request")
    knowledge_ids: Optional[List[StrictStr]] = Field(default=None, description="Selected knowledge ID for this request")
    mentioned_items: Optional[List[InternalHandlerSessionMentionedItemRequest]] = Field(default=None, description="@mentioned knowledge bases and files")
    query: StrictStr = Field(description="Query text for knowledge base search")
    summary_model_id: Optional[StrictStr] = Field(default=None, description="Optional summary model ID for this request (overrides session default)")
    web_search_enabled: Optional[StrictBool] = Field(default=None, description="Whether web search is enabled for this request")
    __properties: ClassVar[List[str]] = ["agent_enabled", "knowledge_base_ids", "knowledge_ids", "mentioned_items", "query", "summary_model_id", "web_search_enabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalHandlerSessionCreateKnowledgeQARequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in mentioned_items (list)
        _items = []
        if self.mentioned_items:
            for _item_mentioned_items in self.mentioned_items:
                if _item_mentioned_items:
                    _items.append(_item_mentioned_items.to_dict())
            _dict['mentioned_items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalHandlerSessionCreateKnowledgeQARequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_enabled": obj.get("agent_enabled"),
            "knowledge_base_ids": obj.get("knowledge_base_ids"),
            "knowledge_ids": obj.get("knowledge_ids"),
            "mentioned_items": [InternalHandlerSessionMentionedItemRequest.from_dict(_item) for _item in obj["mentioned_items"]] if obj.get("mentioned_items") is not None else None,
            "query": obj.get("query"),
            "summary_model_id": obj.get("summary_model_id"),
            "web_search_enabled": obj.get("web_search_enabled")
        })
        return _obj


