# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from weknora.models.github_com_tencent_we_knora_internal_types_fallback_strategy import GithubComTencentWeKnoraInternalTypesFallbackStrategy
from weknora.models.github_com_tencent_we_knora_internal_types_summary_config import GithubComTencentWeKnoraInternalTypesSummaryConfig
from typing import Optional, Set
from typing_extensions import Self

class InternalHandlerSessionSessionStrategy(BaseModel):
    """
    InternalHandlerSessionSessionStrategy
    """ # noqa: E501
    embedding_top_k: Optional[StrictInt] = Field(default=None, description="Number of top results to retrieve from vector search")
    enable_rewrite: Optional[StrictBool] = Field(default=None, description="Whether to enable query rewrite for multi-round conversations")
    fallback_response: Optional[StrictStr] = Field(default=None, description="Fixed response content for fallback")
    fallback_strategy: Optional[GithubComTencentWeKnoraInternalTypesFallbackStrategy] = Field(default=None, description="Strategy to use when no relevant knowledge is found")
    keyword_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Threshold for keyword-based retrieval")
    max_rounds: Optional[StrictInt] = Field(default=None, description="Maximum number of conversation rounds to maintain")
    no_match_prefix: Optional[StrictStr] = Field(default=None, description="Prefix for responses when no match is found")
    rerank_model_id: Optional[StrictStr] = Field(default=None, description="ID of the model used for reranking results")
    rerank_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Threshold for reranking results")
    rerank_top_k: Optional[StrictInt] = Field(default=None, description="Number of top results after reranking")
    summary_model_id: Optional[StrictStr] = Field(default=None, description="ID of the model used for summarization")
    summary_parameters: Optional[GithubComTencentWeKnoraInternalTypesSummaryConfig] = Field(default=None, description="Parameters for the summary model")
    vector_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Threshold for vector-based retrieval")
    __properties: ClassVar[List[str]] = ["embedding_top_k", "enable_rewrite", "fallback_response", "fallback_strategy", "keyword_threshold", "max_rounds", "no_match_prefix", "rerank_model_id", "rerank_threshold", "rerank_top_k", "summary_model_id", "summary_parameters", "vector_threshold"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalHandlerSessionSessionStrategy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of summary_parameters
        if self.summary_parameters:
            _dict['summary_parameters'] = self.summary_parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalHandlerSessionSessionStrategy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "embedding_top_k": obj.get("embedding_top_k"),
            "enable_rewrite": obj.get("enable_rewrite"),
            "fallback_response": obj.get("fallback_response"),
            "fallback_strategy": obj.get("fallback_strategy"),
            "keyword_threshold": obj.get("keyword_threshold"),
            "max_rounds": obj.get("max_rounds"),
            "no_match_prefix": obj.get("no_match_prefix"),
            "rerank_model_id": obj.get("rerank_model_id"),
            "rerank_threshold": obj.get("rerank_threshold"),
            "rerank_top_k": obj.get("rerank_top_k"),
            "summary_model_id": obj.get("summary_model_id"),
            "summary_parameters": GithubComTencentWeKnoraInternalTypesSummaryConfig.from_dict(obj["summary_parameters"]) if obj.get("summary_parameters") is not None else None,
            "vector_threshold": obj.get("vector_threshold")
        })
        return _obj


