# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from weknora.models.github_com_tencent_we_knora_internal_types_model_parameters import GithubComTencentWeKnoraInternalTypesModelParameters
from weknora.models.github_com_tencent_we_knora_internal_types_model_source import GithubComTencentWeKnoraInternalTypesModelSource
from weknora.models.github_com_tencent_we_knora_internal_types_model_type import GithubComTencentWeKnoraInternalTypesModelType
from typing import Optional, Set
from typing_extensions import Self

class InternalHandlerUpdateModelRequest(BaseModel):
    """
    InternalHandlerUpdateModelRequest
    """ # noqa: E501
    description: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    parameters: Optional[GithubComTencentWeKnoraInternalTypesModelParameters] = None
    source: Optional[GithubComTencentWeKnoraInternalTypesModelSource] = None
    type: Optional[GithubComTencentWeKnoraInternalTypesModelType] = None
    __properties: ClassVar[List[str]] = ["description", "name", "parameters", "source", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalHandlerUpdateModelRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of parameters
        if self.parameters:
            _dict['parameters'] = self.parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalHandlerUpdateModelRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "name": obj.get("name"),
            "parameters": GithubComTencentWeKnoraInternalTypesModelParameters.from_dict(obj["parameters"]) if obj.get("parameters") is not None else None,
            "source": obj.get("source"),
            "type": obj.get("type")
        })
        return _obj


