# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InternalHandlerGetSystemInfoResponse(BaseModel):
    """
    InternalHandlerGetSystemInfoResponse
    """ # noqa: E501
    build_time: Optional[StrictStr] = None
    commit_id: Optional[StrictStr] = None
    go_version: Optional[StrictStr] = None
    graph_database_engine: Optional[StrictStr] = None
    keyword_index_engine: Optional[StrictStr] = None
    minio_enabled: Optional[StrictBool] = None
    vector_store_engine: Optional[StrictStr] = None
    version: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["build_time", "commit_id", "go_version", "graph_database_engine", "keyword_index_engine", "minio_enabled", "vector_store_engine", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalHandlerGetSystemInfoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalHandlerGetSystemInfoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "build_time": obj.get("build_time"),
            "commit_id": obj.get("commit_id"),
            "go_version": obj.get("go_version"),
            "graph_database_engine": obj.get("graph_database_engine"),
            "keyword_index_engine": obj.get("keyword_index_engine"),
            "minio_enabled": obj.get("minio_enabled"),
            "vector_store_engine": obj.get("vector_store_engine"),
            "version": obj.get("version")
        })
        return _obj


