# coding: utf-8

"""
    WeKnora API

    WeKnora 知识库管理系统 API 文档

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class InternalHandlerUpdateChunkRequest(BaseModel):
    """
    InternalHandlerUpdateChunkRequest
    """ # noqa: E501
    chunk_index: Optional[StrictInt] = None
    content: Optional[StrictStr] = None
    embedding: Optional[List[Union[StrictFloat, StrictInt]]] = None
    end_at: Optional[StrictInt] = None
    image_info: Optional[StrictStr] = None
    is_enabled: Optional[StrictBool] = None
    start_at: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["chunk_index", "content", "embedding", "end_at", "image_info", "is_enabled", "start_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalHandlerUpdateChunkRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalHandlerUpdateChunkRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chunk_index": obj.get("chunk_index"),
            "content": obj.get("content"),
            "embedding": obj.get("embedding"),
            "end_at": obj.get("end_at"),
            "image_info": obj.get("image_info"),
            "is_enabled": obj.get("is_enabled"),
            "start_at": obj.get("start_at")
        })
        return _obj


